#include "color.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

Color imperial_red;
Color scarlet;
Color indian_red;
Color barn_red;
Color chili_red;
Color ruby;
Color maroon;
Color fire_brick;
Color redwood;
Color carmine;
Color desire;
Color vermilion;
Color raspberry;
Color candy_apple;
Color persian;
Color hibiscus;
Color u_s_flag;
Color ferrari;
Color sangria;
Color mahogany;
Color burgundy;
Color crimson;
Color rust;
Color light_salmon;
Color salmon;
Color dark_salmon;
Color light_coral;
Color red;
Color dark_red;
Color tomato;
Color orange_red;
Color pale_violet_red;
Color light_brick;
Color brick;
Color prismatic_red;
Color prismatic_legacy;
Color prismatic_vermilion_renewal;
Color prismatic_reflections_shade;
Color _49ers_red;
Color cardinals_red;
Color airbnb_red;
Color ajax_red;
Color alabama_crimson;
Color alizarin_crimson;
Color amaranth_red;
Color american_rose;
Color angels_red;
Color almost_apricot_red;
Color arsenal_red;
Color auburn_red;
Color bu_scarlet;
Color bills_red;
Color bittersweet_shimmer_red;
Color blood_red;
Color cg_red; 
Color cadmium_red; 
Color cardinal_red; 
Color carnelian_red;
Color cerise_red; 
Color chiefs_red;
Color chocolate_cosmos_red; 
Color cincinnati_red;
Color cinnabar_red;
Color coke_red;
Color coquelicot_red; 
Color coral_red; 
Color cordovan_red; 
Color crayola_red;
Color electric_crimson;
Color english_red; 
Color falcons_red; 
Color falu_red; 
Color fire_engine_red;
Color flame_red;
Color folly_red;
Color french_puce_red; 
Color fuchsia;
Color fuzzy_wuzzy_red; 
Color garnet_red;
Color harvard_crimson;
Color hollywood_cerise_red;
Color husker_red; 
Color japanese_carmine; 
Color jasper_red; 
Color jelly_bean_red; 
Color kenyan_copper_red; 
Color lava_red;
Color liverpool_red; 
Color lust_red;
Color mit_red;
Color madder_red;
Color pigment_magenta;
Color manchester_united_red;
Color medium_violet_red;
Color munsell_red;
Color ncs_red;
Color nationals_red;
Color oklahoma_crimson;
Color oxblood_red;
Color pastel_red; 
Color penn_red;
Color persian_rose_red;
Color phillies_red;
Color pigment_red;
Color pinterest_red; 
Color popstar_red; 
Color portland_orange_red; 
Color prune_red; 
Color radical_red; 
Color red_devil; 
Color red_sox;
Color rose_red;
Color rosewood_red;
Color rufous_red; 
Color russet_red;
Color rusty_red;
Color sanguine_red;
Color spanish_red;
Color tango_red; 
Color tawny_red;
Color tea_rose_red;
Color terracotta_red;
Color tractor_red; 
Color turkey_red;
Color tuscan_red;
Color upsdell_red; 
Color venetian_red;
Color virgin_lust_red; 
Color wine_red;
Color light_red_ochre; 
Color medium_vermillion; 
Color up_maroon;
Color outrageous_orange_red; 
Color utah_crimson; 
Color dark_orange;
Color vivid_orange;
Color orange_red;
Color tomato;
Color metallic_orange;
Color pumpkin;
Color smashed_pumpkin;
Color yellow_orange;
Color carrot_orange;
Color international_orange;
Color spanish_orange;
Color tangerine;
Color princeton_orange;
Color orioles_orange;
Color deep_saffron;
Color alloy_orange;
Color halloween_orange;
Color tangelo;
Color gamboge;
Color vermilion;
Color medium_vermilion;
Color fulvous;
Color pastel_orange;
Color flame;
Color philippine_orange;
Color beer_orange;
Color chinese_orange;
Color jasper_orange;
Color royal_orange;
Color coral;
Color dark_coral;
Color cadmium_orange;
Color dark_pastel_red;
Color copper_red;
Color university_of_tennessee_orange;
Color rajah;
Color mango_tango;
Color orange_peel;
Color vivid_tangelo;
Color burnt_umber;
Color papaya_whip;
Color bittersweet;
Color persimmon;
Color persian_orange;
Color terracotta;
Color apricot_orange;
Color bronze_orange;
Color browns_orange;
Color buff_orange; 
Color bumblebee_orange;
Color burnt_orange; 
Color butterscotch_orange; 
Color cheese_orange; 
Color chocolate_orange; 
Color cider_orange; 
Color copper_orange; 
Color crayola_orange; 
Color desert_orange; 
Color desert_sand_orange; 
Color dragon_fire_orange; 
Color dull_orange; 
Color giants_orange; 
Color ginger_orange; 
Color golden_gate_bridge_orange;
Color goldenrod_orange;
Color goldfish_orange;
Color honey_orange;
Color hunyadi_orange;
Color koi_orange;
Color light_orange;
Color light_copper_orange;
Color pumpkin_orange;
Color dark_topaz_orange;
Color mahogany_orange;
Color marigold_orange;
Color melon_orange;
Color mimosa_orange;
Color neon_orange;
Color ochre_orange;
Color orange_pale_orange; 
Color orange_paper_orange; 
Color orange_spice_orange; 
Color outrageous_orange; 
Color pantone_orange; 
Color peach_orange; 
Color pepper_orange; 
Color red_fox_orange; 
Color rumba_orange; 
Color safety_orange; 
Color safflower_orange;
Color salamander_orange;
Color salmon_orange; 
Color squash_orange; 
Color sunrise_orange;
Color sunset_orange;
Color syracuse_orange;
Color tawny_orange;
Color tiger_orange;
Color topaz_orange;
Color tree_sap_orange;
Color web_orange;
Color west_side_orange;
Color wheat_orange;
Color xanthous_orange;
Color yam_orange;
Color mecca_orange;
Color lava_orange;
Color dutch_orange;
Color amber;
Color aesthetic_orange;
Color hot_orange;
Color glossy_orange;
Color pure_orange;
Color rustic_orange;
Color baby_orange;
Color irish_orange; 
Color marmalade;
Color vintage_orange;
Color rust;
Color india_saffron;
Color atomic_tangerine;
Color red_orange_ral;
Color willpower_orange;
Color dusty_orange;
Color spring_orange;
Color greek_orange;
Color calm_orange;
Color faded_orange;
Color luminous_bright_orange_ral;
Color sunshine_yellow;
Color canary_yellow;
Color lemon_yellow;
Color goldenrod;
Color saffron;
Color citrine;
Color trombone;
Color light_yellow;
Color lemon_chiffon;
Color flax;
Color light_goldenrod;
Color pale_goldenrod;
Color light_khaki;
Color clover_lime;
Color xanthic;
Color royal_yellow;
Color cream;
Color gold;
Color safety_yellow;
Color laguna;
Color hunyadi_yellow;
Color bright_yellow;
Color greenish_yellow;
Color neon_yellow; 
Color dark_yellow;
Color sand;
Color sunflower;
Color bumblebee;
Color butter;
Color yellow_tan;
Color cyber_yellow;
Color banana;
Color tuscany;
Color honey;
Color dijon;
Color amber;
Color beige;
Color mustard;
Color maximum_yellow;
Color mellow_yellow;
Color unmellow_yellow;
Color lemon_curry;
Color moccasin;
Color orange_yellow;
Color pastel_yellow;
Color taxi_cab_yellow;
Color aureolin;
Color electric_yellow;
Color chartreuse_traditional;
Color titanium_yellow;
Color mikado_yellow;
Color fluorescent_yellow;
Color arylide_yellow;
Color indian_yellow;
Color durian_yellow;
Color minion_yellow;
Color selective_yellow;
Color laser_lemon;
Color munsell_yellow;
Color yellow_rose;
Color very_pale_yellow;
Color earth_yellow;
Color yellow_pantone;
Color tangerine_yellow;
Color bronze_yellow;
Color psychedelic_yellow;
Color maize_yellow_ral;
Color muted_yellow;
Color sulfur_yellow;
Color yellow_jasmine;
Color dusty_yellow;
Color yolk_yellow_pantone;
Color light_chrome_yellow;
Color cadmium_yellow_lemon;
Color vibrant_yellow;
Color yellow_cmyk;
Color fire_yellow;
Color buff_yellow; 
Color yellow_cream;
Color empire_yellow;
Color zinc_yellow_ral;
Color signal_yellow;
Color matte_yellow;
Color aesthetic_yellow;
Color rustic_yellow;
Color pale_yellow;
Color colza_yellow;
Color transparent_yellow;
Color blazing_yellow;
Color tender_yellow;
Color pale_lime_yellow;
Color vintage_yellow;
Color spectrum_yellow;
Color retro_yellow;
Color old_yellow;
Color chinese_yellow;
Color spanish_yellow;
Color refresh_yellow;
Color sun_yellow_ral;
Color baby_yellow;
Color dahlia_yellow_ral; 
Color broom_yellow;
Color camouflage_yellow;
Color trust_yellow;
Color warm_yellow;
Color vivid_yellow;
Color turmeric;
Color sunglow;
Color light_saffron;
Color radioactive;
Color golden_poppy;
Color real_gold;
Color glossy_gold;
Color snapchat_yellow;
Color deep_chrome_yellow_ferrario;
Color melon_yellow;
Color bright_canary_yellow;
Color deep_napoli_yellow;
Color radiant_yellow;
Color daffodil_yellow;
Color mineral_yellow;
Color relax_yellow;
Color rainbow_yellow;
Color deep_yellow;
Color ochre_yellow;
Color dull_yellow;
Color hot_yellow;
Color traffic_yellow_ral;
Color yellow_orange;
Color olive_yellow_ral; 
Color faded_yellow;
Color solid_yellow;
Color golden_yellow_ral;
Color corn;
Color dandelion;
Color icterine;
Color sandstorm;
Color macaroon;
Color urobilin;
Color satin_sheen_gold;
Color school_bus_yellow;
Color british_standard_bs_4800_10_e_51_yellow;
Color mimosa;
Color marigold;
Color daisy_yellow;
Color forest_green;
Color olive;
Color hunter_green;
Color artichoke_green;
Color jungle_green;
Color tropical_rainforest;
Color amazon;
Color deep_jungle_green;
Color medium_jungle_green;
Color dark_jungle_green;
Color moss_green;
Color myrtle_green;
Color pine_green;
Color persian_green;
Color emerald_green;
Color neon_green;
Color sacramento_green;
Color sea_green;
Color sage_green;
Color lime_green;
Color jade_green;
Color fern_green;
Color laurel_green;
Color mint_green;
Color tea_green;
Color army_green;
Color kelly_green;
Color russian_green;
Color paris_green;
Color pakistan_green;
Color midnight_green;
Color india_green;
Color hunter_green;
Color celadon;
Color avocado;
Color harlequin;
Color spring;
Color kaitoke;
Color chateau;
Color dark_moss_green;
Color swamp;
Color mantis;
Color fun;
Color pantone_artichoke_green;
Color viridian;
Color reseda_green;
Color chetwode;
Color shamrock_green;
Color verdun;
Color castleton_green;
Color gin;
Color granny_smith_apple;
Color bitter_lime;
Color bright_mint;
Color bottle_green;
Color cadmium_green;
Color camouflage_green;
Color pear;
Color dollar_bill;
Color inchworm;
Color asparagus;
Color caribbean_green;
Color go_green;
Color phthalo_green;
Color napier_green;
Color feldgrau;
Color green_yellow;
Color malachite;
Color rifle_green;
Color volt;
Color british_racing_green;
Color thyme;
Color chartreuse;
Color corn_green;
Color shrek_green;
Color christmas_green;
Color irish_green;
Color road_sign_green;
Color lightsaber_green;
Color girl_scout_green;
Color tennis_court_green;
Color spring_bud;
Color chinese_green;
Color arctic_lime;
Color nyanza;
Color dark_lemon_lime;
Color crayola_yellow_green; 
Color maximum_green;
Color vivid_lime_green;
Color pistachio;
Color medium_spring_green;
Color sheen_green;
Color la_salle_green;
Color spanish_viridian; 
Color dartmouth_green;
Color pine_needle_color;
Color olive_drab;
Color lawn_green;
Color xanadu;
Color dark_olive_green;
Color dark_sea_green;
Color green_munsell;
Color mughal_green;
Color john_deere_green;
Color office_green;
Color limerick;
Color maximum_green_yellow;
Color french_lime;
Color medium_spring_bud;
Color ufo_green;
Color acid_green;
Color chlorophyll_green;
Color green_lizard;
Color iguana_green;
Color kombu_green;
Color middle_green; 
Color paolo_veronese_green;
Color pullman_green;
Color green_screen;
Color android_green;
Color bitter_lemon;
Color wageningen_green;
Color sap_green;
Color old_moss_green;
Color slimy_green;
Color very_light_malachite_green;
Color dark_spring_green;
Color guppie_green;
Color apple_green;
Color deep_green;
Color medium_sea_green;
Color turquoise_green;
Color turquoise;
Color celeste;
Color light_turquoise;
Color turquoise_blue;
Color medium_turquoise;
Color dark_turquoise;
Color bright_turquoise;
Color powder_blue;
Color sky_blue;
Color electric_blue;
Color air_force_blue_raf;
Color air_force_blue_usaf;
Color us_air_force_academy_blue;
Color beau_blue;
Color baby_blue;
Color baby_blue_eyes;
Color little_boy_blue;
Color tiffany_blue;
Color steel_blue;
Color carolina_blue;
Color turkish_blue;
Color maya_blue;
Color teal;
Color independence_blue;
Color cornflower_blue;
Color sapphire_blue;
Color medium_sapphire;
Color blue_sapphire;
Color dark_sapphire;
Color azure;
Color egyptian_blue;
Color yale_blue;
Color navy_blue;
Color prussian_blue;
Color space_cadet;
Color traditional_royal_blue;
Color queen_blue;
Color imperial_blue;
Color periwinkle;
Color morning_blue;
Color uranian_blue;
Color fluorescent_blue;
Color ruddy_blue;
Color admiral_blue; 
Color aegean_blue;
Color aero_blue;
Color air_superiority_blue;
Color alice_blue;
Color aqua_blue;
Color aquamarine_blue;
Color arctic_blue;
Color argentina_blue;
Color astros_navy;
Color bayern_blue;
Color berry_blue;
Color blue;
Color blue_yonder;
Color bleu_de_france_blue;
Color blue_gray;
Color boeing_blue;
Color braves_navy;
Color brewers_blue;
Color broncos_blue;
Color byzantine_blue;
Color cambridge_blue;
Color capri_blue;
Color cerulean_blue;
Color chelsea_blue; 
Color chlorine_blue; 
Color cobalt_blue; 
Color college_navy;
Color columbia_blue; 
Color crayola_blue; 
Color cyan_blue;
Color dallas_cowboys_blue;
Color dark_blue;
Color delft_blue;
Color dell_blue;
Color denim_blue; 
Color dodgers_blue;
Color dolphins_aqua;
Color duck_blue;
Color duke_blue;
Color electric_indigo;
Color everton_blue;
Color facebook_blue;
Color ford_blue; 
Color general_motors_blue;
Color glaucous_blue;
Color ibm_blue; 
Color ice_blue; 
Color indigo_blue;
Color indigo_dye_blue; 
Color intel_blue; 
Color international_klein_blue; 
Color iris_blue;
Color kc_royals_blue;
Color lapis_blue; 
Color liberty_blue;
Color lowes_blue;
Color magic_blue; 
Color majorelle_blue;
Color marian_blue; 
Color mavericks_blue;
Color medium_blue;
Color medium_slate_blue;
Color millennium_blue;
Color munsell_blue;
Color neon_blue;
Color non_photo_blue;
Color ocean_blue; 
Color oxford_blue;
Color psg_blue; 
Color pacific_blue; 
Color pantone_blue; 
Color peacock_blue; 
Color penn_blue;
Color persian_blue;
Color phthalo_blue; 
Color picotee_blue;
Color polynesian_blue;
Color resolution_blue;
Color robin_egg_blue;
Color savoy_blue;
Color slate_blue;
Color spanish_blue;
Color spruce_blue; 
Color stone_blue; 
Color tottenham_navy;
Color true_blue;
Color tufts_blue;
Color twitter_blue; 
Color ucla_blue;
Color ultramarine_blue;
Color violet_blue;
Color visa_blue; 
Color vivid_sky_blue;
Color warriors_blue;
Color yankees_blue;
Color yinmn_blue; 
Color steel_blue;
Color alaskan_blue;
Color tall_ships_blue;
Color true_purple;
Color thistle;
Color plum;
Color violet;
Color orchid;
Color fuchsia;
Color medium_orchid;
Color medium_purple;
Color blue_violet;
Color dark_violet;
Color dark_orchid;
Color dark_magenta;
Color indigo;
Color veronica;
Color pale_purple;
Color mauve;
Color heliotrope;
Color phlox;
Color purple_pizzazz;
Color liserian_purple;
Color mulberry;
Color pearly_purple;
Color purpureus;
Color northwestern_purple;
Color ksu_purple;
Color pomp_and_power;
Color mardi_gras;
Color eminence;
Color pansy_purple;
Color palatinate;
Color dark_purple;
Color byzantium;
Color african_violet;
Color amethyst;
Color chinese_violet;
Color english_violet;
Color russian_violet;
Color fairy_tale;
Color fandango;
Color french_mauve;
Color affair;
Color iris;
Color long_distance;
Color prince_charming;
Color lipstick_stain;
Color pompadour;
Color grape_color;
Color wine;
Color pizza_edge;
Color tyrian_purple;
Color ultra_violet;
Color studio;
Color electric_purple;
Color eggplant;
Color periwinkle_purple;
Color sangria;
Color raisin;
Color mountbatten_pink;
Color fuchsia_blue;
Color good_tax;
Color jam;
Color ripe_plum;
Color heather;
Color magenta_purple;
Color old_lavender;
Color rebecca_purple;
Color razzmic_berry_purple;
Color wine_dregs_purple;
Color regalia_purple;
Color twilight_lavender_purple;
Color traditional_purple;
Color spanish_violet_purple;
Color imperial_purple;
Color japanese_violet_purple;
Color munsell_purple;
Color deep_ruby_purple;
Color purple_heart;
Color lavender_blush;
Color early_bird;
Color lilac;
Color purple_taupe;
Color cyber_grape_purple;
Color kingfisher_daisy;
Color seance;
Color lavender_gray;
Color hopbush;
Color tacao;
Color brilliant_purple;
Color murasaki_purple;
Color blackish_purple;
Color lovely_purple;
Color vulgar_purple_grape_jelly;
Color university_of_central_arkansas_purple; 
Color fedex_purple; 
Color carolina_plum;
Color kalamata;
Color black_currant;
Color purple_4;
Color strong_purple;
Color pale_purple;
Color vivid_reddish_purple;
Color medium_purple_3;
Color middle_purple;
Color cardinal;
Color embassy_purple;
Color lakers_purple;
Color amaranth_purple;
Color purple_navy;
Color insolent_purple;
Color smyrna_purple; 
Color east_carolina_university_purple;
Color little_princess;
Color aesthetic_purple;
Color kikyo_iru;
Color metallic_purple;
Color hot_purple;
Color faded_purple;
Color mythical_purple;
Color languid_lavender;
Color mauveine;
Color blue_lilac;
Color dark_byzantium;
Color luxury_purple;
Color aztech_purple;
Color baltimore_ravens_purple;
Color deep_magenta;
Color deep_purple;
Color rustic_purple;
Color sunset_purple;
Color dull_purple;
Color traffic_purple;
Color matte_purple;
Color purple_violet;
Color purple_cmyk; 
Color ocean_purple; 
Color shiny_purple;
Color autumn_purple;
Color watermelon;
Color flamingo;
Color coral;
Color salmon;
Color pastel_pink;
Color light_pink;
Color cherry_blossom;
Color bubblegum;
Color baby_pink;
Color dark_pink;
Color bright_pink;
Color rouge;
Color neon_pink;
Color blush;
Color fuchsia;
Color mauve;
Color orchid;
Color magenta;
Color hot_pink;
Color carnation;
Color tulip_pink;
Color tea_rose;
Color cotton_candy;
Color cameo_pink;
Color french_pink;
Color strawberry;
Color persian_pink;
Color new_york_pink;
Color indian_red;
Color munsell_red;
Color cardinal;
Color crayola_red;
Color crimson;
Color ruby;
Color redwood;
Color rusty_red;
Color amaranth;
Color bright_maroon;
Color burnt_sienna;
Color candy_pink;
Color cherry_pink;
Color chestnut;
Color dark_coral;
Color dark_pastel_red;
Color dark_terra_cotta; 
Color dark_salmon;
Color lemonade;
Color peach;
Color crepe;
Color piggy_pink;
Color deep_pink;
Color dust_storm;
Color nadeshiko_pink;
Color rose_quartz;
Color wild_strawberry;
Color razzmatazz;
Color rose_taupe;
Color rubine_red;
Color hollywood_cerise;
Color mexican_pink;
Color steel_pink;
Color rose_gold;
Color rose_bonbon;
Color barbie_pink;
Color mulberry;
Color razzle_dazzle_rose;
Color fandango;
Color puce;
Color old_rose;
Color rosewood;
Color taffy;
Color turkish_rose;
Color punch;
Color paradise_pink;
Color raspberry_rose;
Color light_crimson;
Color pink_sherbet;
Color tickle_me_pink;
Color thulian_pink;
Color brilliant_rose;
Color lace;
Color smitten;
Color your;
Color careys;
Color oyster;
Color shimmering_blush;
Color sea;
Color brink;
Color hippie;
Color light_deep_pink;
Color wild_orchid;
Color cerise_pink;
Color shocking_pink;
Color hit;
Color lady;
Color neon_fuchsia;
Color ultra_pink;
Color schauss_pink;
Color ruddy_pink;
Color pink_pearl;
Color lavender_rose;
Color shampoo;
Color spanish_pink;
Color valentine_pink;
Color silvery_pink;
Color melon;
Color milano;
Color sweet_pink;
Color knockout_pink;
Color grapefruit_pink;
Color champagne_pink;
Color lip_pink;
Color passion_pink;
Color nude_pink;
Color rosy_pink;
Color gold_pink;
Color misty_rose;
Color mauvelous;
Color light_blush;
Color copper_rose;
Color raspberry_glace;
Color debian_red;
Color ruber;
Color vanilla_ice;
Color light_hot_pink;
Color super_pink;
Color china_rose;
Color deep_pruce;
Color french_fuchsia;
Color almond; 
Color auburn;
Color beaver;
Color beige;
Color bisque;
Color bistre;
Color bole;
Color bone;
Color brass;
Color bronze;
Color burnt_umber;
Color cafe_au_lait;
Color cafe_noir;
Color champagne;
Color cinnamon;
Color coffee;
Color deep_coffee; 
Color copper;
Color dark_brown;
Color taupe;
Color tan_;
Color chestnut;
Color sand;
Color ecru;
Color fawn;
Color ginger;
Color golden_brown;
Color khaki;
Color mahogany;
Color ochre;
Color light_brown;
Color saddle_brown;
Color wheat;
Color russet;
Color rust;
Color sepia;
Color sienna;
Color antique_brass;
Color burlywood;
Color peru;
Color tumbleweed;
Color dark_vanilla;
Color tuscan_brown;
Color wood_brown;
Color deer;
Color chamoisee;
Color dirt;
Color coconut;
Color windsor_tan;
Color rufous;
Color acorn;
Color ash_brown;
Color ash_gray;
Color ash_white;
Color baked_bread;
Color baked_potato;
Color bamboo;
Color bark;
Color beeswax;
Color beige_linen;
Color birdseed;
Color bitter_chocolate;
Color brandy;
Color brown_bear;
Color brown_beige;
Color brown_coffee;
Color brown_gray;
Color brown_metal;
Color brown_red;
Color brown_rust;
Color brown_stone;
Color brown_sugar;
Color brownie;
Color brownish_gray;
Color brownish_red;
Color burnt_almond;
Color burnt_henna;
Color butter_toast;
Color buttercream;
Color buttery_brown;
Color camel;
Color canadian_maple;
Color canvas_brown;
Color caramel;
Color caramel_apple;
Color carnal_brown;
Color cashmere;
Color chai;
Color chamomile;
Color chicory;
Color chocolate;
Color cinnamon_toast;
Color citrus_brown;
Color cotton;
Color croissant;
Color dark_beige;
Color dark_chestnut;
Color dark_khaki;
Color dark_sand;
Color dark_wood;
Color deep_brown;
Color deep_taupe;
Color desert_gray;
Color dried_moss;
Color dull_brown;
Color fall_harvest;
Color feather_brown;
Color firewood;
Color fortune_cookie;
Color french_beige;
Color ginger_ale;
Color golden_fog;
Color gray_brown;
Color grayish_brown;
Color hardwood;
Color hawaiian_brown;
Color heavy_brown;
Color honey_brown;
Color iced_coffee;
Color kobicha;
Color lace;
Color latte;
Color light_taupe;
Color maple_sugar;
Color maple_syrup;
Color mars_brown;
Color medium_brown;
Color mojave_desert;
Color abbey;
Color ash_gray;
Color asphalt;
Color black;
Color black_bean;
Color black_cat;
Color black_cow;
Color black_eel;
Color black_olive;
Color charcoal;
Color charleston_green;
Color dark_jungle_green;
Color dim_gray;
Color ebony;
Color eerie_black;
Color granite;
Color gray;
Color gray_cloud;
Color gray_wolf;
Color gunmetal;
Color iridium;
Color jet;
Color licorice;
Color midnight;
Color night;
Color oil;
Color old_burgundy;
Color onyx;
Color outer_space;
Color raisin_black;
Color smoky_black;
Color taupe;
Color vampire_gray;
Color black_leather_jacket;
Color cafe_americano;
Color blackberry;
Color lamp_black;
Color army_uniform;
Color slate;
Color pitch_black;
Color spider;
Color metal;
Color grease;
Color crow;
Color black_rock;
Color basalt_black;
Color neutral_black;
Color black_denim;
Color vampire_black;
Color cool_black;
Color panda_black;
Color frost_black;
Color ink_black_ral;
Color raven;
Color leather;
Color sable;
Color power_black;
Color soot;
Color jade;
Color true_black;
Color premium_black;
Color obsidian;
Color black_grain;
Color black_magic;
Color iron_black;
Color rich_black_fogra29;
Color warm_black;
Color black_coral;
Color black_shadows;
Color black_raspberry;
Color kombu_green;
Color zinnwaldite_brown;
Color dark_slate_gray;
Color dark_charcoal;
Color russian_violet;
Color dark_sienna;
Color alien_black;
Color black_chocolate;
Color blue_charcoal;
Color gothic_grape;
Color metropolis;
Color night_shadow;
Color off_black;
Color dark_raisin;
Color tea_bag;
Color electric_black;
Color tech_black;
Color dull_black;
Color dark_black;
Color natural_black;
Color retro_black;
Color black_green_ral;
Color deep_black;
Color refresh_black;
Color rustic_black;
Color rose_ebony;
Color liver;
Color purple_taupe;
Color black_pearl; 
Color black_russian;
Color aesthetic_black;
Color signal_black_ral;
Color cafe_noir;
Color luxury_black;
Color bright_black;
Color black_blue_ral;
Color glossy_black;
Color ivory_black;
Color pastel_black;
Color fashion_black;
Color graphite_black_ral;
Color black_gray;
Color black_hole;
Color kokushoku;
Color kurotobi;
Color _void;
Color wet_suit;
Color yacht_club_black;
Color young_night;
Color blackstrap_molasses;
Color carbon_black;
Color cynical_black;
Color black_plum;
Color reversed_gray;
Color stout;
Color tornado_cloud;
Color walnut_hull;
Color tap_shoe;
Color woodsmoke;
Color black_red;
Color wind_cave;
Color heavy_gray;
Color arsenic;
Color ash_gray;
Color battleship_gray;
Color black_coral;
Color blue_gray;
Color cadet_gray;
Color carbon_gray;
Color charcoal;
Color cinereous;
Color cool_gray;
Color dark_gray;
Color davys_gray;
Color deep_space_sparkle;
Color dim_gray;
Color gainsboro;
Color gray;
Color gray_cloud;
Color gray_dolphin;
Color gray_goose;
Color gray_green;
Color gray_wolf;
Color glaucous;
Color gunmetal;
Color jet;
Color jet_gray;
Color light_gray;
Color light_slate_gray;
Color marengo;
Color medium_gray;
Color nevada;
Color nickel;
Color old_silver;
Color outer_space;
Color rocket_metallic;
Color scorpion;
Color silver;
Color silver_chalice;
Color slate_blue;
Color slate_gray;
Color smoke;
Color smokey_gray;
Color sonic_gray;
Color spanish_gray;
Color stone_gray;
Color stormcloud;
Color taupe_gray;
Color timberwolf;
Color onyx;
Color paynes_gray;
Color platinum;
Color pink_gray;
Color purple_gray;
Color rose_quartz;
Color vampire_gray;
Color white_smoke;
Color xanadu;
Color bright_gray;
Color x11_gray;
Color dark_silver;
Color pastel_gray;
Color dusty_gray;
Color misty_gray;
Color white_gray;
Color vintage_gray;
Color gentle_gray;
Color zombie_gray;
Color lavender_gray;
Color perfect_gray;
Color graphite_gray;
Color rustic_gray;
Color echo;
Color window_gray;
Color silk_gray;
Color light_gunmetal;
Color silver_pink;
Color matte_silver;
Color rhythm;
Color pure_silver;
Color dark_charcoal;
Color best_gray;
Color agreeable_gray;
Color oxford_gray;
Color antique_pewter;
Color warm_gray;
Color sage_gray;
Color dull_gray;
Color rich_gray;
Color ice_gray;
Color gray_cmyk;
Color solid_gray;
Color electric_gray;
Color templeton_gray;
Color chrome;
Color sea_gray;
Color glossy_gray;
Color anvil_gray;
Color chameleon_gray;
Color cement_gray;
Color steel_gray;
Color dorian_gray;
Color gun_smoke_gray;
Color camouflage_gray;
Color fashion_gray;
Color neutral_gray;
Color revere_pewter;
Color olive_gray;
Color metallic_gray;
Color french_gray;
Color iron;
Color pale_smoke;
Color bone;
Color heather;
Color true_silver;
Color power_gray;
Color storm_gray;
Color ultimate_gray;
Color rhino;
Color harbor_gray;
Color seal;
Color anchor;
Color abalone;
Color fossil;
Color mink;
Color trout;
Color thunder;
Color shades_on;
Color lava;
Color stone_eagle;
Color ice_cube;
Color porpoise;
Color flint;
Color dove;
Color gray_owl;
Color coin;
Color fog;
Color laid_back_gray;
Color white;
Color ghost_white;
Color white_smoke;
Color baby_powder;
Color snow;
Color ivory;
Color floral_white;
Color seashell;
Color cornsilk;
Color old_lace;
Color cream;
Color beige;
Color parchment;
Color antique_white;
Color champagne;
Color eggshell;
Color dutch_white;
Color bone;
Color vanilla;
Color flax;
Color navajo_white;
Color alabaster;
Color chiffon;
Color unresolved_problem;
Color old_wood;
Color rose_white;
Color vista_white;
Color link_white;
Color spring;
Color snow_drift;
Color peppermint;
Color merino;
Color half_and_half;
Color island_spice;
Color soft_peach;
Color harp;
Color titan_white;
Color audience_anger;
Color orange_white;
Color cough_mixture;
Color albescent_white;
Color coconut;
Color pink_salt;
Color frost;
Color linen;
Color rice;
Color daisy;
Color powder;
Color pearl;
Color paris_white;
Color cup_cake;
Color white_dove;
Color white_whisper;
Color lexicon;
Color greek_villa;
Color white_diamond;
Color winter_white;
Color spatial_white;
Color hog_bristle_quarter;
Color simply_white;
Color oyster_white;
Color white_on_white;
Color lexicon_quarter;
Color alice_blue;
Color honeydew;
Color mint_cream;
Color milk;
Color pomelo_white;
Color anti_flash_white;
Color magnolia;
Color azure;
Color huntington_white;
Color acadia_white;
Color gainsboro;
Color mercury;
Color lavender_blush;
Color isabelline;
Color bubbles;
Color glitter;
Color platinum;
Color cosmic_latte;
Color blanched_almond;
Color light_yellow;
Color natural_white;
Color vivid_white;
Color white_wisp;
Color azureish_white;
Color timberwolf;
Color papaya_whip;
Color antique_white_usa;
Color cola;
Color atrium_white;
Color cascading_white;
Color cotton_ball;
Color photon_white;
Color white_heat;
Color whitewash;
Color shadow_white;
Color abbey_white;
Color acoustic_white;
Color aircraft_white;
Color ceramic;
Color coconut_butter;
Color abstract_white;
Color bright_white;
Color broken_white;
Color brilliant_white;
Color commercial_white;
Color feather_white;
Color swan_white;
Color polar_bear;
Color paper_white;
Color pacific_pearl;
Color night_white;
Color delicate_white;
Color coconut_white;
Color cake_batter;
Color white_sand;
Color stone_white;
Color white_chocolate;
Color retro_white;

RgbColor rgb_color_make(unsigned int hex)
{
	unsigned char r = (hex >> 16) & 0xFF;
	unsigned char g = (hex >> 8) & 0xFF;
	unsigned char b = (hex) & 0xFF;
	RgbColor result = { r, g, b, 255 };
	return result;
}

Color color_make(unsigned int hex)
{
	float r = ((hex >> 16) & 0xFF) / 255.0;
	float g = ((hex >> 8) & 0xFF) / 255.0;
	float b = ((hex) & 0xFF) / 255.0;
	Color result = { r, g, b, 1 };
	return result;
}

char* rgb_color_term(RgbColor color, char* text)
{
	char* result = malloc(sizeof(char) * (32 + strlen(text)));
	sprintf(result, "\x1b[38;2;%d;%d;%dm%s\x1b[0m", color.r, color.g, color.b, text);
	return result;
}

char* color_term(Color color, char* text)
{
	char* result = malloc(sizeof(char) * (32 + strlen(text)));
	sprintf(result, "\x1b[38;2;%.0f;%.0f;%.0fm%s\x1b[0m", color.r * 255, color.g * 255, color.b * 255, text);
	return result;
}

void color_init()
{
	imperial_red = color_make(0xed2939);
	scarlet = color_make(0xff2400);
	indian_red = color_make(0xcd5c5c);
	barn_red = color_make(0x7c0a02);
	chili_red = color_make(0xc21807);
	ruby = color_make(0xe0115f);
	maroon = color_make(0x800000);
	fire_brick = color_make(0xb22222);
	redwood = color_make(0xa45a52);
	carmine = color_make(0x960018);
	desire = color_make(0xea3c53);
	vermilion = color_make(0x7e191b);
	raspberry = color_make(0xd21f3c);
	candy_apple = color_make(0xff0800);
	persian = color_make(0xca3433);
	hibiscus = color_make(0xb43757);
	u_s_flag = color_make(0xbf0a30);
	ferrari = color_make(0xff2800);
	sangria = color_make(0x5e1914);
	mahogany = color_make(0x420d09);
	burgundy = color_make(0x8d021f);
	crimson = color_make(0xb80f0a);
	rust = color_make(0x933a16);
	light_salmon = color_make(0xffa07a);
	salmon = color_make(0xfa8072);
	dark_salmon = color_make(0xe9967a);
	light_coral = color_make(0xf08080);
	red = color_make(0xff0000);
	dark_red = color_make(0x8b0000);
	tomato = color_make(0xff6347);
	orange_red = color_make(0xff4500);
	pale_violet_red = color_make(0xdb7093);
	light_brick = color_make(0xfb607f);
	brick = color_make(0x7e2811);
	prismatic_red = color_make(0xd03d33);
	prismatic_legacy = color_make(0xba1607);
	prismatic_vermilion_renewal = color_make(0xca0123);
	prismatic_reflections_shade = color_make(0xff3c28);
	_49ers_red = color_make(0xaa0000);
	cardinals_red = color_make(0xbd2031);
	airbnb_red = color_make(0xff5a5f);
	ajax_red = color_make(0xd2122e);
	alabama_crimson = color_make(0x9e1b32);
	alizarin_crimson = color_make(0xe32636);
	amaranth_red = color_make(0xf4364c);
	american_rose = color_make(0xff033e);
	angels_red = color_make(0xba0021);
	almost_apricot_red = color_make(0xe5b39b);
	arsenal_red = color_make(0xdb0007);
	auburn_red = color_make(0xa52a2a);
	bu_scarlet = color_make(0xcc0000);
	bills_red = color_make(0xc60c30);
	bittersweet_shimmer_red = color_make(0xbf4f51);
	blood_red = color_make(0x660000);
	cg_red = color_make(0xe03c31); 
	cadmium_red = color_make(0xe30022); 
	cardinal_red = color_make(0xc41e3a); 
	carnelian_red = color_make(0xb31b1b);
	cerise_red = color_make(0xde3163); 
	chiefs_red = color_make(0xe31837);
	chocolate_cosmos_red = color_make(0x58111a); 
	cincinnati_red = color_make(0xc6011f);
	cinnabar_red = color_make(0xe44d2e);
	coke_red = color_make(0xf40009);
	coquelicot_red = color_make(0xff3800); 
	coral_red = color_make(0xff7f50); 
	cordovan_red = color_make(0x893f45); 
	crayola_red = color_make(0xee204d);
	electric_crimson = color_make(0xff003f);
	english_red = color_make(0xab4b52); 
	falcons_red = color_make(0xa71930); 
	falu_red = color_make(0x801818); 
	fire_engine_red = color_make(0xce2029);
	flame_red = color_make(0xe25822);
	folly_red = color_make(0xff004f);
	french_puce_red = color_make(0x4e1609); 
	fuchsia = color_make(0xff00ff);
	fuzzy_wuzzy_red = color_make(0xcc6666); 
	garnet_red = color_make(0x733635);
	harvard_crimson = color_make(0xa51c30);
	hollywood_cerise_red = color_make(0xf400a1);
	husker_red = color_make(0xe41c38); 
	japanese_carmine = color_make(0x9d2933); 
	jasper_red = color_make(0xd73b3e); 
	jelly_bean_red = color_make(0xda614e); 
	kenyan_copper_red = color_make(0x7c1c05); 
	lava_red = color_make(0xcf1020);
	liverpool_red = color_make(0xc8102e); 
	lust_red = color_make(0xe62020);
	mit_red = color_make(0xa31f34);
	madder_red = color_make(0xa50021);
	pigment_magenta = color_make(0xff0090);
	manchester_united_red = color_make(0xda291c);
	medium_violet_red = color_make(0xc71585);
	munsell_red = color_make(0xf2003c);
	ncs_red = color_make(0xc40233);
	nationals_red = color_make(0xab0003);
	oklahoma_crimson = color_make(0x841617);
	oxblood_red = color_make(0x800020);
	pastel_red = color_make(0xff6961); 
	penn_red = color_make(0x990000);
	persian_rose_red = color_make(0xfe28a2);
	phillies_red = color_make(0xe81828);
	pigment_red = color_make(0xed1c24);
	pinterest_red = color_make(0xe60023); 
	popstar_red = color_make(0xbe4f62); 
	portland_orange_red = color_make(0xff5a36); 
	prune_red = color_make(0x701c1c); 
	radical_red = color_make(0xff355e); 
	red_devil = color_make(0x860111); 
	red_sox = color_make(0xbd3039);
	rose_red = color_make(0xc21e56);
	rosewood_red = color_make(0x65000b);
	rufous_red = color_make(0xa81c07); 
	russet_red = color_make(0x80461b);
	rusty_red = color_make(0xda2c43);
	sanguine_red = color_make(0xbc3f4a);
	spanish_red = color_make(0xe60026);
	tango_red = color_make(0xe4717a); 
	tawny_red = color_make(0xcd5700);
	tea_rose_red = color_make(0xf88379);
	terracotta_red = color_make(0xe2725b);
	tractor_red = color_make(0xfd0e35); 
	turkey_red = color_make(0xa91101);
	tuscan_red = color_make(0x7c3030);
	upsdell_red = color_make(0xae2029); 
	venetian_red = color_make(0xc80815);
	virgin_lust_red = color_make(0xe4181e); 
	wine_red = color_make(0x722f37);
	light_red_ochre = color_make(0xe97451); 
	medium_vermillion = color_make(0xd9603b); 
	up_maroon = color_make(0x7b1113);
	outrageous_orange_red = color_make(0xff6e4a); 
	utah_crimson = color_make(0xd3003f); 
	dark_orange = color_make(0xff8c00);
	vivid_orange = color_make(0xff5e0e);
	orange_red = color_make(0xff4500);
	tomato = color_make(0xff6347);
	metallic_orange = color_make(0xe26310);
	pumpkin = color_make(0xf5761a);
	smashed_pumpkin = color_make(0xfd673a);
	yellow_orange = color_make(0xffa836);
	carrot_orange = color_make(0xed9121);
	international_orange = color_make(0xff4f00);
	spanish_orange = color_make(0xf06105);
	tangerine = color_make(0xf78702);
	princeton_orange = color_make(0xff8f00);
	orioles_orange = color_make(0xfb4f14);
	deep_saffron = color_make(0xffa52c);
	alloy_orange = color_make(0xc35214);
	halloween_orange = color_make(0xee5921);
	tangelo = color_make(0xfc4c02);
	gamboge = color_make(0xe89611);
	vermilion = color_make(0xd74826);
	medium_vermilion = color_make(0xcf5b2e);
	fulvous = color_make(0xe68000);
	pastel_orange = color_make(0xfeba4f);
	flame = color_make(0xe34a27);
	philippine_orange = color_make(0xf26e01);
	beer_orange = color_make(0xf28f1c);
	chinese_orange = color_make(0xeb6841);
	jasper_orange = color_make(0xe89149);
	royal_orange = color_make(0xff9944);
	coral = color_make(0xff7f50);
	dark_coral = color_make(0xd75341);
	cadmium_orange = color_make(0xe6812f);
	dark_pastel_red = color_make(0xc34723);
	copper_red = color_make(0xd97448);
	university_of_tennessee_orange = color_make(0xf77f00);
	rajah = color_make(0xfaba5f);
	mango_tango = color_make(0xfb8842);
	orange_peel = color_make(0xff9f00);
	vivid_tangelo = color_make(0xec7625);
	burnt_umber = color_make(0x8a3324);
	papaya_whip = color_make(0xfff1d7);
	bittersweet = color_make(0xfe6f5e);
	persimmon = color_make(0xec5800);
	persian_orange = color_make(0xd99058);
	terracotta = color_make(0xe2725b);
	apricot_orange = color_make(0xfbceb1);
	bronze_orange = color_make(0xcd7f32);
	browns_orange = color_make(0xff3c00);
	buff_orange = color_make(0xf2ca85); 
	bumblebee_orange = color_make(0xffc82a);
	burnt_orange = color_make(0xcc5500); 
	butterscotch_orange = color_make(0xd99151); 
	cheese_orange = color_make(0xffa600); 
	chocolate_orange = color_make(0xd2691e); 
	cider_orange = color_make(0xd8a175); 
	copper_orange = color_make(0xbb772e); 
	crayola_orange = color_make(0xff7538); 
	desert_orange = color_make(0xed8e4a); 
	desert_sand_orange = color_make(0xedc9af); 
	dragon_fire_orange = color_make(0xfd652d); 
	dull_orange = color_make(0xdb804e); 
	giants_orange = color_make(0xfe5a1d); 
	ginger_orange = color_make(0xb06500); 
	golden_gate_bridge_orange = color_make(0xc0362c);
	goldenrod_orange = color_make(0xdaa520);
	goldfish_orange = color_make(0xff9913);
	honey_orange = color_make(0xffbd31);
	hunyadi_orange = color_make(0xe8ac41);
	koi_orange = color_make(0xd15837);
	light_orange = color_make(0xfed8b1);
	light_copper_orange = color_make(0xf6cba0);
	pumpkin_orange = color_make(0xff7518);
	dark_topaz_orange = color_make(0xeabd8c);
	mahogany_orange = color_make(0xc04000);
	marigold_orange = color_make(0xeaa221);
	melon_orange = color_make(0xdf9166);
	mimosa_orange = color_make(0xffca4b);
	neon_orange = color_make(0xffad00);
	ochre_orange = color_make(0xc99700);
	orange_pale_orange = color_make(0xffdfbf); 
	orange_paper_orange = color_make(0xfee8d6); 
	orange_spice_orange = color_make(0xd76b00); 
	outrageous_orange = color_make(0xff6e4a); 
	pantone_orange = color_make(0xfe5000); 
	peach_orange = color_make(0xffcc99); 
	pepper_orange = color_make(0xe77d22); 
	red_fox_orange = color_make(0x985629); 
	rumba_orange = color_make(0xf06631); 
	safety_orange = color_make(0xff6700); 
	safflower_orange = color_make(0xfdae44);
	salamander_orange = color_make(0xf05e23);
	salmon_orange = color_make(0xff8066); 
	squash_orange = color_make(0xe89362); 
	sunrise_orange = color_make(0xe67451);
	sunset_orange = color_make(0xfd5e53);
	syracuse_orange = color_make(0xd44500);
	tawny_orange = color_make(0xb25a38);
	tiger_orange = color_make(0xf96815);
	topaz_orange = color_make(0xffc87c);
	tree_sap_orange = color_make(0xcc7711);
	web_orange = color_make(0xffa500);
	west_side_orange = color_make(0xff9916);
	wheat_orange = color_make(0xf5deb3);
	xanthous_orange = color_make(0xf1b42f);
	yam_orange = color_make(0xe17e45);
	mecca_orange = color_make(0xbd5745);
	lava_orange = color_make(0xf76806);
	dutch_orange = color_make(0xff9b00);
	amber = color_make(0xffc600);
	aesthetic_orange = color_make(0xf4ab6a);
	hot_orange = color_make(0xff6e00);
	glossy_orange = color_make(0xe78400);
	pure_orange = color_make(0xff8000);
	rustic_orange = color_make(0xd78c3d);
	baby_orange = color_make(0xfcbe85);
	irish_orange = color_make(0xf5883f); 
	marmalade = color_make(0xd16002);
	vintage_orange = color_make(0xc9995d);
	rust = color_make(0xb7410e);
	india_saffron = color_make(0xff9933);
	atomic_tangerine = color_make(0xff9966);
	red_orange_ral = color_make(0xb6481c);
	willpower_orange = color_make(0xfd5602);
	dusty_orange = color_make(0xe27a53);
	spring_orange = color_make(0xfd963d);
	greek_orange = color_make(0xe06e04);
	calm_orange = color_make(0xfab972);
	faded_orange = color_make(0xcd946a);
	luminous_bright_orange_ral = color_make(0xffb700);
	sunshine_yellow = color_make(0xfffd37);
	canary_yellow = color_make(0xffef00);
	lemon_yellow = color_make(0xfdff00);
	goldenrod = color_make(0xdaa520);
	saffron = color_make(0xf4c430);
	citrine = color_make(0xe4d00a);
	trombone = color_make(0xd2b55b);
	light_yellow = color_make(0xffffe0);
	lemon_chiffon = color_make(0xfffacd);
	flax = color_make(0xeedc82);
	light_goldenrod = color_make(0xfafad2);
	pale_goldenrod = color_make(0xeee8aa);
	light_khaki = color_make(0xf0e68c);
	clover_lime = color_make(0xfce883);
	xanthic = color_make(0xeeed09);
	royal_yellow = color_make(0xfada5e);
	cream = color_make(0xffffcc);
	gold = color_make(0xffd700);
	safety_yellow = color_make(0xeed202);
	laguna = color_make(0xf8e473);
	hunyadi_yellow = color_make(0xe8ac41);
	bright_yellow = color_make(0xfffd01);
	greenish_yellow = color_make(0xeeea62);
	neon_yellow = color_make(0xcfff04); 
	dark_yellow = color_make(0xd5b60a);
	sand = color_make(0xe2ca76);
	sunflower = color_make(0xffda03);
	bumblebee = color_make(0xfce205);
	butter = color_make(0xfffd74);
	yellow_tan = color_make(0xffe36e);
	cyber_yellow = color_make(0xffd300);
	banana = color_make(0xffe135);
	tuscany = color_make(0xfcd12a);
	honey = color_make(0xffc30b);
	dijon = color_make(0xc49102);
	amber = color_make(0xffbf00);
	beige = color_make(0xf5f5dc);
	mustard = color_make(0xfedc56);
	maximum_yellow = color_make(0xfafa37);
	mellow_yellow = color_make(0xf8de7e);
	unmellow_yellow = color_make(0xffff66);
	lemon_curry = color_make(0xcca01d);
	moccasin = color_make(0xffe4b5);
	orange_yellow = color_make(0xffad01);
	pastel_yellow = color_make(0xfffe71);
	taxi_cab_yellow = color_make(0xfdb813);
	aureolin = color_make(0xfdee00);
	electric_yellow = color_make(0xffff33);
	chartreuse_traditional = color_make(0xdfff00);
	titanium_yellow = color_make(0xeee600);
	mikado_yellow = color_make(0xffc40c);
	fluorescent_yellow = color_make(0xccff00);
	arylide_yellow = color_make(0xe9d66b);
	indian_yellow = color_make(0xe3a857);
	durian_yellow = color_make(0xe1bd27);
	minion_yellow = color_make(0xf5e050);
	selective_yellow = color_make(0xffba00);
	laser_lemon = color_make(0xfefe22);
	munsell_yellow = color_make(0xefcc00);
	yellow_rose = color_make(0xfff000);
	very_pale_yellow = color_make(0xffffbf);
	earth_yellow = color_make(0xe1a95f);
	yellow_pantone = color_make(0xfedf00);
	tangerine_yellow = color_make(0xffcc00);
	bronze_yellow = color_make(0x737000);
	psychedelic_yellow = color_make(0xfff53d);
	maize_yellow_ral = color_make(0xdb9100);
	muted_yellow = color_make(0xe0d268);
	sulfur_yellow = color_make(0xe8de35);
	yellow_jasmine = color_make(0xceb00d);
	dusty_yellow = color_make(0xd4cc9a);
	yolk_yellow_pantone = color_make(0xe2b051);
	light_chrome_yellow = color_make(0xffca37);
	cadmium_yellow_lemon = color_make(0xfff23e);
	vibrant_yellow = color_make(0xffda29);
	yellow_cmyk = color_make(0xffff00);
	fire_yellow = color_make(0xfede17);
	buff_yellow = color_make(0xf1bf70); 
	yellow_cream = color_make(0xefdc75);
	empire_yellow = color_make(0xf7d000);
	zinc_yellow_ral = color_make(0xf2cb2e);
	signal_yellow = color_make(0xf2a900);
	matte_yellow = color_make(0xedd94c);
	aesthetic_yellow = color_make(0xefd033);
	rustic_yellow = color_make(0xe2c400);
	pale_yellow = color_make(0xffffa7);
	colza_yellow = color_make(0xeeb700);
	transparent_yellow = color_make(0xf4ecc2);
	blazing_yellow = color_make(0xfee715);
	tender_yellow = color_make(0xedeeb7);
	pale_lime_yellow = color_make(0xdfe69f);
	vintage_yellow = color_make(0xcba92b);
	spectrum_yellow = color_make(0xfce517);
	retro_yellow = color_make(0xf0e27b);
	old_yellow = color_make(0xc8af55);
	chinese_yellow = color_make(0xffb200);
	spanish_yellow = color_make(0xf9d73d);
	refresh_yellow = color_make(0xffe992);
	sun_yellow_ral = color_make(0xea9300);
	baby_yellow = color_make(0xfcef91);
	dahlia_yellow_ral = color_make(0xf39b1b); 
	broom_yellow = color_make(0xdba400);
	camouflage_yellow = color_make(0x978942);
	trust_yellow = color_make(0xeebe15);
	warm_yellow = color_make(0xf4e98c);
	vivid_yellow = color_make(0xffe302);
	turmeric = color_make(0xf0ca28);
	sunglow = color_make(0xffcc33);
	light_saffron = color_make(0xffe797);
	radioactive = color_make(0xfae500);
	golden_poppy = color_make(0xfcc200);
	real_gold = color_make(0xe2bf36);
	glossy_gold = color_make(0xfae481);
	snapchat_yellow = color_make(0xfffc00);
	deep_chrome_yellow_ferrario = color_make(0xffb045);
	melon_yellow = color_make(0xff9c00);
	bright_canary_yellow = color_make(0xffe41e);
	deep_napoli_yellow = color_make(0xffcf99);
	radiant_yellow = color_make(0xfc9e21);
	daffodil_yellow = color_make(0xe28d00);
	mineral_yellow = color_make(0xd39c43);
	relax_yellow = color_make(0xf3e496);
	rainbow_yellow = color_make(0xf5de10);
	deep_yellow = color_make(0xeace09);
	ochre_yellow = color_make(0xb5904b);
	dull_yellow = color_make(0xdeca57);
	hot_yellow = color_make(0xffda00);
	traffic_yellow_ral = color_make(0xefb700);
	yellow_orange = color_make(0xd56f00);
	olive_yellow_ral = color_make(0x9d8f65); 
	faded_yellow = color_make(0xece3a1);
	solid_yellow = color_make(0xffe81c);
	golden_yellow_ral = color_make(0xdd9f00);
	corn = color_make(0xfbec5d);
	dandelion = color_make(0xf0e130);
	icterine = color_make(0xfcf75e);
	sandstorm = color_make(0xecd540);
	macaroon = color_make(0xf9e076);
	urobilin = color_make(0xe1ad21);
	satin_sheen_gold = color_make(0xcba135);
	school_bus_yellow = color_make(0xffd800);
	british_standard_bs_4800_10_e_51_yellow = color_make(0xedc001);
	mimosa = color_make(0xfff4bc);
	marigold = color_make(0xfcb810);
	daisy_yellow = color_make(0xf8dc75);
	forest_green = color_make(0x0b6623);
	olive = color_make(0x708238);
	hunter_green = color_make(0x3f704d);
	artichoke_green = color_make(0x8f9779);
	jungle_green = color_make(0x29ab87);
	tropical_rainforest = color_make(0x00755e);
	amazon = color_make(0x3b7a57);
	deep_jungle_green = color_make(0x004b49);
	medium_jungle_green = color_make(0x1c352d);
	dark_jungle_green = color_make(0x1a2421);
	moss_green = color_make(0x8a9a5b);
	myrtle_green = color_make(0x317873);
	pine_green = color_make(0x01796f);
	persian_green = color_make(0x00a693);
	emerald_green = color_make(0x50c878);
	neon_green = color_make(0x39ff14);
	sacramento_green = color_make(0x043927);
	sea_green = color_make(0x2e8b57);
	sage_green = color_make(0x9dc183);
	lime_green = color_make(0xc7ea46);
	jade_green = color_make(0x00a86b);
	fern_green = color_make(0x4f7942);
	laurel_green = color_make(0xa9ba9d);
	mint_green = color_make(0x98fb98);
	tea_green = color_make(0xd0f0c0);
	army_green = color_make(0x4b5320);
	kelly_green = color_make(0x4cbb17);
	russian_green = color_make(0x679267);
	paris_green = color_make(0x50c878);
	pakistan_green = color_make(0x006600);
	midnight_green = color_make(0x004953);
	india_green = color_make(0x138808);
	hunter_green = color_make(0x355e3b);
	celadon = color_make(0xace1af);
	avocado = color_make(0x568203);
	harlequin = color_make(0x3fff00);
	spring = color_make(0x00f0a8);
	kaitoke = color_make(0x004830);
	chateau = color_make(0x48a860);
	dark_moss_green = color_make(0x4a5d23);
	swamp = color_make(0xa8c090);
	mantis = color_make(0x74c365);
	fun = color_make(0x007848);
	pantone_artichoke_green = color_make(0x4b6f44);
	viridian = color_make(0x609078);
	reseda_green = color_make(0x6c7c59);
	chetwode = color_make(0xf0fff0);
	shamrock_green = color_make(0x009e60);
	verdun = color_make(0x487800);
	castleton_green = color_make(0x00563b);
	gin = color_make(0xd8e4bc);
	granny_smith_apple = color_make(0xa8e4a0);
	bitter_lime = color_make(0xbfff00);
	bright_mint = color_make(0x4fffb0);
	bottle_green = color_make(0x006a4e);
	cadmium_green = color_make(0x006b3c);
	camouflage_green = color_make(0x78866b);
	pear = color_make(0xd1e231);
	dollar_bill = color_make(0x85bb65);
	inchworm = color_make(0xb2ec5d);
	asparagus = color_make(0x87a96b);
	caribbean_green = color_make(0x00cc99);
	go_green = color_make(0x00ab66);
	phthalo_green = color_make(0x123524);
	napier_green = color_make(0x2a8000);
	feldgrau = color_make(0x4d5d53);
	green_yellow = color_make(0xadff2f);
	malachite = color_make(0x0bda51);
	rifle_green = color_make(0x444c38);
	volt = color_make(0xceff00);
	british_racing_green = color_make(0x004225);
	thyme = color_make(0x5edc1f);
	chartreuse = color_make(0x7fff00);
	corn_green = color_make(0x71a92c);
	shrek_green = color_make(0xc4d300);
	christmas_green = color_make(0x00873e);
	irish_green = color_make(0x009a44);
	road_sign_green = color_make(0x01735c);
	lightsaber_green = color_make(0x2ff924);
	girl_scout_green = color_make(0x00ae58);
	tennis_court_green = color_make(0x6c935c);
	spring_bud = color_make(0xa7fc00);
	chinese_green = color_make(0xd0db61);
	arctic_lime = color_make(0xd0ff14);
	nyanza = color_make(0xe9ffdb);
	dark_lemon_lime = color_make(0x76ba1b);
	crayola_yellow_green = color_make(0xacdf87); 
	maximum_green = color_make(0x4c9a2a);
	vivid_lime_green = color_make(0xa4de02);
	pistachio = color_make(0x93c572);
	medium_spring_green = color_make(0x00fa9a);
	sheen_green = color_make(0x8fd400);
	la_salle_green = color_make(0x087830);
	spanish_viridian = color_make(0x007f5c); 
	dartmouth_green = color_make(0x00703c);
	pine_needle_color = color_make(0x454d32);
	olive_drab = color_make(0x6b8e23);
	lawn_green = color_make(0x7cfc00);
	xanadu = color_make(0x738678);
	dark_olive_green = color_make(0x556b2f);
	dark_sea_green = color_make(0x8fbc8f);
	green_munsell = color_make(0x00a877);
	mughal_green = color_make(0x306030);
	john_deere_green = color_make(0x367c2b);
	office_green = color_make(0x008000);
	limerick = color_make(0x9dc209);
	maximum_green_yellow = color_make(0xd9e650);
	french_lime = color_make(0x9efd38);
	medium_spring_bud = color_make(0xc9dc87);
	ufo_green = color_make(0x3cd070);
	acid_green = color_make(0xb0bf1a);
	chlorophyll_green = color_make(0x4aff00);
	green_lizard = color_make(0xa7f432);
	iguana_green = color_make(0x71bc78);
	kombu_green = color_make(0x354230);
	middle_green = color_make(0x4d8c57); 
	paolo_veronese_green = color_make(0x009b7d);
	pullman_green = color_make(0x3b331c);
	green_screen = color_make(0x00b140);
	android_green = color_make(0xa4c639);
	bitter_lemon = color_make(0xcae00d);
	wageningen_green = color_make(0x34b233);
	sap_green = color_make(0x507d2a);
	old_moss_green = color_make(0x867e36);
	slimy_green = color_make(0x299617);
	very_light_malachite_green = color_make(0x64e986);
	dark_spring_green = color_make(0x177245);
	guppie_green = color_make(0x00ff7f);
	apple_green = color_make(0x8db600);
	deep_green = color_make(0x056608);
	medium_sea_green = color_make(0x3cb371);
	turquoise_green = color_make(0xa0d6b4);
	turquoise = color_make(0x40e0d0);
	celeste = color_make(0xb2ffff);
	light_turquoise = color_make(0xafeeee);
	turquoise_blue = color_make(0x00ffef);
	medium_turquoise = color_make(0x48d1cc);
	dark_turquoise = color_make(0x00ced1);
	bright_turquoise = color_make(0x08e8de);
	powder_blue = color_make(0xb0e0e6);
	sky_blue = color_make(0xadd8e6);
	electric_blue = color_make(0x7df9ff);
	air_force_blue_raf = color_make(0x5d8aa8);
	air_force_blue_usaf = color_make(0x00308f);
	us_air_force_academy_blue = color_make(0x004f98);
	beau_blue = color_make(0xbcd4e6);
	baby_blue = color_make(0x89cff0);
	baby_blue_eyes = color_make(0xa1caf1);
	little_boy_blue = color_make(0x6ca0dc);
	tiffany_blue = color_make(0x81d8d0);
	steel_blue = color_make(0x4682b4);
	carolina_blue = color_make(0x4b9cd3);
	turkish_blue = color_make(0x4f97a3);
	maya_blue = color_make(0x73c2fb);
	teal = color_make(0x008080);
	independence_blue = color_make(0x4c516d);
	cornflower_blue = color_make(0x6495ed);
	sapphire_blue = color_make(0x0f52ba);
	medium_sapphire = color_make(0x2d5da1);
	blue_sapphire = color_make(0x126180);
	dark_sapphire = color_make(0x082567);
	azure = color_make(0x007fff);
	egyptian_blue = color_make(0x1034a6);
	yale_blue = color_make(0x00356b);
	navy_blue = color_make(0x000080);
	prussian_blue = color_make(0x003153);
	space_cadet = color_make(0x1d2951);
	traditional_royal_blue = color_make(0x002366);
	queen_blue = color_make(0x436b95);
	imperial_blue = color_make(0x005a92);
	periwinkle = color_make(0xccccff);
	morning_blue = color_make(0x8da399);
	uranian_blue = color_make(0xafdbf5);
	fluorescent_blue = color_make(0x15f4ee);
	ruddy_blue = color_make(0x76abdf);
	admiral_blue = color_make(0x2c3863); 
	aegean_blue = color_make(0x4e6e81);
	aero_blue = color_make(0xc9ffe5);
	air_superiority_blue = color_make(0x72a0c1);
	alice_blue = color_make(0xf0f8ff);
	aqua_blue = color_make(0x0affff);
	aquamarine_blue = color_make(0x6bcae2);
	arctic_blue = color_make(0xc6e6fb);
	argentina_blue = color_make(0x6cb4ee);
	astros_navy = color_make(0x002d62);
	bayern_blue = color_make(0x0066b2);
	berry_blue = color_make(0x4f86f7);
	blue = color_make(0x0000ff);
	blue_yonder = color_make(0x5072a7);
	bleu_de_france_blue = color_make(0x318ce7);
	blue_gray = color_make(0x6699cc);
	boeing_blue = color_make(0x0039a6);
	braves_navy = color_make(0x13274f);
	brewers_blue = color_make(0x0a2351);
	broncos_blue = color_make(0x002244);
	byzantine_blue = color_make(0x3457d5);
	cambridge_blue = color_make(0xa3c1ad);
	capri_blue = color_make(0x00bfff);
	cerulean_blue = color_make(0x2a52be);
	chelsea_blue = color_make(0x034694); 
	chlorine_blue = color_make(0x0cafff); 
	cobalt_blue = color_make(0x0047ab); 
	college_navy = color_make(0x002244);
	columbia_blue = color_make(0xb9d9eb); 
	crayola_blue = color_make(0x1f75fe); 
	cyan_blue = color_make(0x00ffff);
	dallas_cowboys_blue = color_make(0x041e42);
	dark_blue = color_make(0x00008b);
	delft_blue = color_make(0x1f305e);
	dell_blue = color_make(0x0076ce);
	denim_blue = color_make(0x1560bd); 
	dodgers_blue = color_make(0x005a9c);
	dolphins_aqua = color_make(0x008e97);
	duck_blue = color_make(0x007791);
	duke_blue = color_make(0x012169);
	electric_indigo = color_make(0x6f00ff);
	everton_blue = color_make(0x003399);
	facebook_blue = color_make(0x1877f2);
	ford_blue = color_make(0x2c3968); 
	general_motors_blue = color_make(0x073980);
	glaucous_blue = color_make(0x6082b6);
	ibm_blue = color_make(0x0530ad); 
	ice_blue = color_make(0x99ffff); 
	indigo_blue = color_make(0x3f00ff);
	indigo_dye_blue = color_make(0x00416a); 
	intel_blue = color_make(0x0071c5); 
	international_klein_blue = color_make(0x002fa7); 
	iris_blue = color_make(0x5a4fcf);
	kc_royals_blue = color_make(0x004687);
	lapis_blue = color_make(0x26619c); 
	liberty_blue = color_make(0x545aa7);
	lowes_blue = color_make(0x004792);
	magic_blue = color_make(0x0077c0); 
	majorelle_blue = color_make(0x6050dc);
	marian_blue = color_make(0xe1ebee); 
	mavericks_blue = color_make(0x00538c);
	medium_blue = color_make(0x0000cd);
	medium_slate_blue = color_make(0x7b68ee);
	millennium_blue = color_make(0x002244);
	munsell_blue = color_make(0x0093af);
	neon_blue = color_make(0x4d4dff);
	non_photo_blue = color_make(0xa4dded);
	ocean_blue = color_make(0x009dc4); 
	oxford_blue = color_make(0x002147);
	psg_blue = color_make(0x004170); 
	pacific_blue = color_make(0x1ca9c9); 
	pantone_blue = color_make(0x0018a8); 
	peacock_blue = color_make(0x005f69); 
	penn_blue = color_make(0x011f5b);
	persian_blue = color_make(0x1c39bb);
	phthalo_blue = color_make(0x000f89); 
	picotee_blue = color_make(0x2e2787);
	polynesian_blue = color_make(0x224c98);
	resolution_blue = color_make(0x002387);
	robin_egg_blue = color_make(0x00cccc);
	savoy_blue = color_make(0x4b61d1);
	slate_blue = color_make(0x6a5acd);
	spanish_blue = color_make(0x0070bb);
	spruce_blue = color_make(0x617178); 
	stone_blue = color_make(0x819ea8); 
	tottenham_navy = color_make(0x132257);
	true_blue = color_make(0x2d68c4);
	tufts_blue = color_make(0x3e8ede);
	twitter_blue = color_make(0x1da1f2); 
	ucla_blue = color_make(0x2774ae);
	ultramarine_blue = color_make(0x120a8f);
	violet_blue = color_make(0x324ab2);
	visa_blue = color_make(0x1a1f71); 
	vivid_sky_blue = color_make(0x00ccff);
	warriors_blue = color_make(0x1d428a);
	yankees_blue = color_make(0x0c2340);
	yinmn_blue = color_make(0x2e5090); 
	steel_blue = color_make(0x4682b4);
	alaskan_blue = color_make(0x6da9d2);
	tall_ships_blue = color_make(0x0e81b9);
	true_purple = color_make(0x6a0dad);
	thistle = color_make(0xd8bfd8);
	plum = color_make(0xdda0dd);
	violet = color_make(0x8f00ff);
	orchid = color_make(0xda70d6);
	fuchsia = color_make(0xff00ff);
	medium_orchid = color_make(0xba55d3);
	medium_purple = color_make(0x9370db);
	blue_violet = color_make(0x8a2be2);
	dark_violet = color_make(0x9400d3);
	dark_orchid = color_make(0x9932cc);
	dark_magenta = color_make(0x8b008b);
	indigo = color_make(0x4b0082);
	veronica = color_make(0xa020f0);
	pale_purple = color_make(0xfae6fa);
	mauve = color_make(0xe0b0ff);
	heliotrope = color_make(0xdf73ff);
	phlox = color_make(0xdf00ff);
	purple_pizzazz = color_make(0xfe4eda);
	liserian_purple = color_make(0xde6fa1);
	mulberry = color_make(0xc54b8c);
	pearly_purple = color_make(0xb768a2);
	purpureus = color_make(0x9a4eae);
	northwestern_purple = color_make(0x4e2a84);
	ksu_purple = color_make(0x512888);
	pomp_and_power = color_make(0x86608e);
	mardi_gras = color_make(0x880085);
	eminence = color_make(0x6c3082);
	pansy_purple = color_make(0x78184a);
	palatinate = color_make(0x72246c);
	dark_purple = color_make(0x301934);
	byzantium = color_make(0x702963);
	african_violet = color_make(0xb284be);
	amethyst = color_make(0x9966cc);
	chinese_violet = color_make(0x856088);
	english_violet = color_make(0x563c5c);
	russian_violet = color_make(0x32174d);
	fairy_tale = color_make(0xf2c1d1);
	fandango = color_make(0xb53389);
	french_mauve = color_make(0xd473d4);
	affair = color_make(0x6f4685);
	iris = color_make(0x9867c5);
	long_distance = color_make(0x6f456e);
	prince_charming = color_make(0x493f5e);
	lipstick_stain = color_make(0x8e4785);
	pompadour = color_make(0x720058);
	grape_color = color_make(0x6f2da8);
	wine = color_make(0x2c041c);
	pizza_edge = color_make(0x9a2ca0);
	tyrian_purple = color_make(0x66023c);
	ultra_violet = color_make(0x645394);
	studio = color_make(0x7851a9);
	electric_purple = color_make(0xbf00ff);
	eggplant = color_make(0x311432);
	periwinkle_purple = color_make(0xbe93e4);
	sangria = color_make(0x4d0f28);
	raisin = color_make(0x290916);
	mountbatten_pink = color_make(0x997a8d);
	fuchsia_blue = color_make(0x9c51b6);
	good_tax = color_make(0xc9a0ff);
	jam = color_make(0x67032f);
	ripe_plum = color_make(0x410056);
	heather = color_make(0x9e7bb5);
	magenta_purple = color_make(0xa32cc4);
	old_lavender = color_make(0x796878);
	rebecca_purple = color_make(0x663399);
	razzmic_berry_purple = color_make(0x8d4e85);
	wine_dregs_purple = color_make(0x673147);
	regalia_purple = color_make(0x522d80);
	twilight_lavender_purple = color_make(0x8a496b);
	traditional_purple = color_make(0x8e4585);
	spanish_violet_purple = color_make(0x4c2882);
	imperial_purple = color_make(0x602f6b);
	japanese_violet_purple = color_make(0x5b3256);
	munsell_purple = color_make(0x9f00c5);
	deep_ruby_purple = color_make(0x843f5b);
	purple_heart = color_make(0x7442c8);
	lavender_blush = color_make(0xfff0f5);
	early_bird = color_make(0xcea2fd);
	lilac = color_make(0xb65fcf);
	purple_taupe = color_make(0x50404d);
	cyber_grape_purple = color_make(0x58427c);
	kingfisher_daisy = color_make(0x653780);
	seance = color_make(0x61346b);
	lavender_gray = color_make(0xb6b5d8);
	hopbush = color_make(0xd05fad);
	tacao = color_make(0x6f3096);
	brilliant_purple = color_make(0xd399e6);
	murasaki_purple = color_make(0x4f284b);
	blackish_purple = color_make(0x291e29);
	lovely_purple = color_make(0x7f38ec);
	vulgar_purple_grape_jelly = color_make(0x3e2f84);
	university_of_central_arkansas_purple = color_make(0x4f2d7f); 
	fedex_purple = color_make(0x660099); 
	carolina_plum = color_make(0x9b84a1);
	kalamata = color_make(0x705160);
	black_currant = color_make(0x540e32);
	purple_4 = color_make(0x551a8b);
	strong_purple = color_make(0x875692);
	pale_purple = color_make(0xaa98a9);
	vivid_reddish_purple = color_make(0x870074);
	medium_purple_3 = color_make(0x8968cd);
	middle_purple = color_make(0xd982b5);
	cardinal = color_make(0x8a244e);
	embassy_purple = color_make(0x3b343c);
	lakers_purple = color_make(0x552582);
	amaranth_purple = color_make(0xab274f);
	purple_navy = color_make(0x4e5180);
	insolent_purple = color_make(0x682e3c);
	smyrna_purple = color_make(0xa2627a); 
	east_carolina_university_purple = color_make(0x592a8a);
	little_princess = color_make(0xe9dce5);
	aesthetic_purple = color_make(0x502380);
	kikyo_iru = color_make(0x5d3f6a);
	metallic_purple = color_make(0x520e7d);
	hot_purple = color_make(0xa420d0);
	faded_purple = color_make(0x795f80);
	mythical_purple = color_make(0x53277e);
	languid_lavender = color_make(0xd6cadd);
	mauveine = color_make(0x8d029b);
	blue_lilac = color_make(0x7b679a);
	dark_byzantium = color_make(0x5d3954);
	luxury_purple = color_make(0x743089);
	aztech_purple = color_make(0x893bff);
	baltimore_ravens_purple = color_make(0x280353);
	deep_magenta = color_make(0xcc00cc);
	deep_purple = color_make(0x524f81);
	rustic_purple = color_make(0x593163);
	sunset_purple = color_make(0xa865b5);
	dull_purple = color_make(0x9861a5);
	traffic_purple = color_make(0x913073);
	matte_purple = color_make(0x392a48);
	purple_violet = color_make(0x47243c);
	purple_cmyk = color_make(0x6a317f); 
	ocean_purple = color_make(0x6e2d91); 
	shiny_purple = color_make(0xb941ff);
	autumn_purple = color_make(0x834468);
	watermelon = color_make(0xfc6c85);
	flamingo = color_make(0xfc8eac);
	coral  = color_make(0xf88379);
	salmon = color_make(0xff9999);
	pastel_pink  = color_make(0xffd1dc);
	light_pink  = color_make(0xffb6c1);
	cherry_blossom = color_make(0xffb7c5);
	bubblegum = color_make(0xffc1cc);
	baby_pink  = color_make(0xf4c2c2);
	dark_pink  = color_make(0xe75480);
	bright_pink  = color_make(0xff007f);
	rouge = color_make(0xa94064);
	neon_pink  = color_make(0xff6ec7);
	blush = color_make(0xde5d83);
	fuchsia  = color_make(0xc154c1);
	mauve = color_make(0xe0b0ff);
	orchid = color_make(0xda70d6);
	magenta = color_make(0xff00ff);
	hot_pink  = color_make(0xff69b4);
	carnation = color_make(0xffa6c9);
	tulip_pink = color_make(0xff8e8e);
	tea_rose  = color_make(0xf4c2c2);
	cotton_candy  = color_make(0xffbcd9);
	cameo_pink = color_make(0xefbbcc);
	french_pink = color_make(0xf64a8a);
	strawberry = color_make(0xe8888a);
	persian_pink = color_make(0xf77fbe);
	new_york_pink  = color_make(0xdd8374);
	indian_red = color_make(0xcd5c5c);
	munsell_red = color_make(0xf2003c);
	cardinal  = color_make(0xc41e3a);
	crayola_red = color_make(0xee204d);
	crimson   = color_make(0xdc143c);
	ruby  = color_make(0xe0115f);
	redwood = color_make(0xa45a52);
	rusty_red = color_make(0xda2c43);
	amaranth = color_make(0xe52b50);
	bright_maroon = color_make(0xc32148);
	burnt_sienna = color_make(0xe97451);
	candy_pink = color_make(0xe4717a);
	cherry_pink  = color_make(0xde3163);
	chestnut  = color_make(0xcd5c5c);
	dark_coral = color_make(0xcd5b45);
	dark_pastel_red = color_make(0xc23b22);
	dark_terra_cotta = color_make(0xcc4e5c); 
	dark_salmon  = color_make(0xe9967a);
	lemonade = color_make(0xf2dbe7);
	peach = color_make(0xfad1af);
	crepe  = color_make(0xf89883);
	piggy_pink = color_make(0xfddde6);
	deep_pink = color_make(0xff1493);
	dust_storm = color_make(0xe5ccc9);
	nadeshiko_pink = color_make(0xf6adc6);
	rose_quartz = color_make(0xaa98a9);
	wild_strawberry = color_make(0xff43a4);
	razzmatazz = color_make(0xe3256b);
	rose_taupe = color_make(0x905d5d);
	rubine_red = color_make(0xd10056);
	hollywood_cerise = color_make(0xf400a1);
	mexican_pink = color_make(0xe4007c);
	steel_pink = color_make(0xcc3366);
	rose_gold = color_make(0xb76e79);
	rose_bonbon = color_make(0xf9429e);
	barbie_pink = color_make(0xe0218a);
	mulberry = color_make(0xc54b8c);
	razzle_dazzle_rose = color_make(0xff33cc);
	fandango = color_make(0xb53389);
	puce = color_make(0xcc8899);
	old_rose = color_make(0xc08081);
	rosewood = color_make(0x9e4244);
	taffy = color_make(0xfa86c4);
	turkish_rose = color_make(0xb57281);
	punch = color_make(0xf25278);
	paradise_pink = color_make(0xe63e62);
	raspberry_rose = color_make(0xb3446c);
	light_crimson = color_make(0xf56991);
	pink_sherbet = color_make(0xf78fa7);
	tickle_me_pink = color_make(0xfc89ac);
	thulian_pink = color_make(0xde6fa1);
	brilliant_rose = color_make(0xff55a3);
	lace = color_make(0xffd8f0);
	smitten = color_make(0xc84186);
	your = color_make(0xffc0c0);
	careys = color_make(0xd8a8a8);
	oyster = color_make(0xf0d8d8);
	shimmering_blush = color_make(0xd98695);
	sea = color_make(0xf09090);
	brink = color_make(0xff6090);
	hippie = color_make(0xa84860);
	light_deep_pink = color_make(0xff5ccd);
	wild_orchid = color_make(0xd470a2);
	cerise_pink = color_make(0xec3b83);
	shocking_pink = color_make(0xfc0fc0);
	hit = color_make(0xffa878);
	lady = color_make(0xf0c0a8);
	neon_fuchsia = color_make(0xfe4164);
	ultra_pink = color_make(0xff6fff);
	schauss_pink = color_make(0xff91af);
	ruddy_pink = color_make(0xe18e96);
	pink_pearl = color_make(0xe7accf);
	lavender_rose = color_make(0xfba0e3);
	shampoo = color_make(0xffcff1);
	spanish_pink = color_make(0xf7bfbe);
	valentine_pink = color_make(0xe6a6be);
	silvery_pink = color_make(0xdcb5b4);
	melon = color_make(0xf7bcac);
	milano = color_make(0xd95d67);
	sweet_pink = color_make(0xee918d);
	knockout_pink = color_make(0xff3ea5);
	grapefruit_pink = color_make(0xe0707c);
	champagne_pink = color_make(0xf6e1d3);
	lip_pink = color_make(0xdbac98);
	passion_pink = color_make(0xce74a7);
	nude_pink = color_make(0xddc0b4);
	rosy_pink = color_make(0xff66cc);
	gold_pink = color_make(0xe6c7c2);
	misty_rose = color_make(0xffe4e1);
	mauvelous = color_make(0xef98aa);
	light_blush = color_make(0xf1abb9);
	copper_rose = color_make(0x996666);
	raspberry_glace = color_make(0x915f6d);
	debian_red = color_make(0xd70a53);
	ruber = color_make(0xce4676);
	vanilla_ice = color_make(0xf38fa9);
	light_hot_pink = color_make(0xffb3de);
	super_pink = color_make(0xcf6ba9);
	china_rose = color_make(0xa8516e);
	deep_pruce = color_make(0xa95c68);
	french_fuchsia = color_make(0xfd3f92);
	almond = color_make(0xefdecd); 
	auburn = color_make(0xa52a2a);
	beaver = color_make(0x9f8170);
	beige = color_make(0xf5f5dc);
	bisque  = color_make(0xffe4c4);
	bistre  = color_make(0x3d2b1f);
	bole = color_make(0x79443b);
	bone = color_make(0xe3dac9);
	brass = color_make(0xb5a642);
	bronze  = color_make(0xcd7f32);
	burnt_umber = color_make(0x8a3324);
	cafe_au_lait = color_make(0xa67b5b);
	cafe_noir = color_make(0x4b3621);
	champagne = color_make(0xfad6a5);
	cinnamon  = color_make(0xd2691e);
	coffee = color_make(0x6f4e37);
	deep_coffee = color_make(0x704241); 
	copper = color_make(0xb87333);
	dark_brown = color_make(0x654321);
	taupe  = color_make(0x483c32);
	tan_ = color_make(0xd2b48c);
	chestnut = color_make(0xcd5c5c);
	sand = color_make(0xf6d7b0);
	ecru = color_make(0xc2b280);
	fawn  = color_make(0xe5aa70);
	ginger = color_make(0xb06500);
	golden_brown = color_make(0x996515);
	khaki = color_make(0xc3b091);
	mahogany = color_make(0xc04000);
	ochre = color_make(0xcc7722);
	light_brown = color_make(0xb5651d);
	saddle_brown = color_make(0x8b4513);
	wheat = color_make(0xf5deb3);
	russet = color_make(0x80461b);
	rust = color_make(0xb7410e);
	sepia = color_make(0x704214);
	sienna = color_make(0xa0522d);
	antique_brass = color_make(0xcd9575);
	burlywood = color_make(0xdeb887);
	peru = color_make(0xcd853f);
	tumbleweed = color_make(0xdeaa88);
	dark_vanilla = color_make(0xd1bea8);
	tuscan_brown = color_make(0x6f4e37);
	wood_brown = color_make(0xc19a6b);
	deer = color_make(0xba8759);
	chamoisee = color_make(0xa0785a);
	dirt = color_make(0x9b7653);
	coconut = color_make(0x965a3e);
	windsor_tan = color_make(0xa75502);
	rufous = color_make(0xa81c07);
	acorn = color_make(0xd7a98c);
	ash_brown = color_make(0x98623c);
	ash_gray = color_make(0xc1b5a9);
	ash_white = color_make(0xe9e4d4);
	baked_bread = color_make(0xdacba9);
	baked_potato = color_make(0xb69e87);
	bamboo = color_make(0xe3dec6);
	bark = color_make(0x996633);
	beeswax = color_make(0xe9d7ab);
	beige_linen = color_make(0xe2dac6);
	birdseed = color_make(0xe2c28e);
	bitter_chocolate = color_make(0x9e5b40);
	brandy = color_make(0xdcb68a);
	brown_bear = color_make(0x7f6244);
	brown_beige = color_make(0xcc8833);
	brown_coffee = color_make(0x4a2c2a);
	brown_gray = color_make(0x8d8468);
	brown_metal = color_make(0xbbada1);
	brown_red = color_make(0x922b05);
	brown_rust = color_make(0xaf593e);
	brown_stone = color_make(0x593c39);
	brown_sugar = color_make(0xa17249);
	brownie = color_make(0x964b00);
	brownish_gray = color_make(0x86775f);
	brownish_red = color_make(0x9e3623);
	burnt_almond = color_make(0xb0724a);
	burnt_henna = color_make(0x7e392f);
	butter_toast = color_make(0xd2ad84);
	buttercream = color_make(0xefe0cd);
	buttery_brown = color_make(0xf1ebda);
	camel = color_make(0xc69f59);
	canadian_maple = color_make(0xcab266);
	canvas_brown = color_make(0xbb8855);
	caramel = color_make(0xaf6f09);
	caramel_apple = color_make(0xb87a59);
	carnal_brown = color_make(0xbb8866);
	cashmere = color_make(0xd1b399);
	chai = color_make(0xb1832f);
	chamomile = color_make(0xdac395);
	chicory = color_make(0xa78658);
	chocolate = color_make(0x7b3f00);
	cinnamon_toast = color_make(0x8d7d77);
	citrus_brown = color_make(0xd7c275);
	cotton = color_make(0xfaf4d4);
	croissant = color_make(0xc4ab86);
	dark_beige = color_make(0xac9362);
	dark_chestnut = color_make(0x986960);
	dark_khaki = color_make(0x9b8f55);
	dark_sand = color_make(0x9f7d4f);
	dark_wood = color_make(0x855e42);
	deep_brown = color_make(0x410200);
	deep_taupe = color_make(0x7b6660);
	desert_gray = color_make(0xb8a487);
	dried_moss = color_make(0xccb97e);
	dull_brown = color_make(0x876e4b);
	fall_harvest = color_make(0xa78a59);
	feather_brown = color_make(0xb8ad9e);
	firewood = color_make(0xcebaa8);
	fortune_cookie = color_make(0xe0c5a1);
	french_beige = color_make(0xa67b50);
	ginger_ale = color_make(0xc9a86a);
	golden_fog = color_make(0xf0ead2);
	gray_brown = color_make(0x7f7053);
	grayish_brown = color_make(0x7a6a4f);
	hardwood = color_make(0x937a62);
	hawaiian_brown = color_make(0x99522c);
	heavy_brown = color_make(0x73624a);
	honey_brown = color_make(0xba9238);
	iced_coffee = color_make(0xb18f6a);
	kobicha = color_make(0x6b4423);
	lace = color_make(0xeae3d2);
	latte = color_make(0xc5a582);
	light_taupe = color_make(0xb38b6d);
	maple_sugar = color_make(0xc9a38d);
	maple_syrup = color_make(0xbb9351);
	mars_brown = color_make(0xad6242);
	medium_brown = color_make(0x7f5112);
	mojave_desert = color_make(0xc7b595);
	abbey = color_make(0x494f55);
	ash_gray = color_make(0x666362);
	asphalt = color_make(0x0c0404);
	black = color_make(0x000000);
	black_bean = color_make(0x3d0c02);
	black_cat = color_make(0x413839);
	black_cow = color_make(0x4c4646);
	black_eel = color_make(0x463e3f);
	black_olive = color_make(0x3b3c36);
	charcoal = color_make(0x36454f);
	charleston_green = color_make(0x232b2b);
	dark_jungle_green = color_make(0x1a2421);
	dim_gray = color_make(0x696969);
	ebony = color_make(0x555d50);
	eerie_black = color_make(0x1b1b1b);
	granite = color_make(0x676767);
	gray = color_make(0x808080);
	gray_cloud = color_make(0xb6b6b4);
	gray_wolf = color_make(0x504a4b);
	gunmetal = color_make(0x2c3539);
	iridium = color_make(0x3d3c3a);
	jet = color_make(0x343434);
	licorice = color_make(0x1a1110);
	midnight = color_make(0x2b1b17);
	night = color_make(0x0c090a);
	oil = color_make(0x3b3131);
	old_burgundy = color_make(0x43302e);
	onyx = color_make(0x353839);
	outer_space = color_make(0x414a4c);
	raisin_black = color_make(0x242124);
	smoky_black = color_make(0x100c08);
	taupe = color_make(0x483c32);
	vampire_gray = color_make(0x565051);
	black_leather_jacket = color_make(0x253529);
	cafe_americano = color_make(0x362819);
	blackberry = color_make(0x3a3a38);
	lamp_black = color_make(0x2e473b);
	army_uniform = color_make(0x353f3e);
	slate = color_make(0x26282a);
	pitch_black = color_make(0x27251f);
	spider = color_make(0x040200);
	metal = color_make(0x0e0c0a);
	grease = color_make(0x080806);
	crow = color_make(0x0d0907);
	black_rock = color_make(0x010127);
	basalt_black = color_make(0x4d423e);
	neutral_black = color_make(0x0b0b0b);
	black_denim = color_make(0x191c27);
	vampire_black = color_make(0x0f0404);
	cool_black = color_make(0x151922);
	panda_black = color_make(0x3c4748);
	frost_black = color_make(0x191c20);
	ink_black_ral = color_make(0x212122);
	raven = color_make(0x050301);
	leather = color_make(0x0b0705);
	sable = color_make(0x060606);
	power_black = color_make(0x0e0c01);
	soot = color_make(0x160d08);
	jade = color_make(0x000302);
	true_black = color_make(0x0a0b0b);
	premium_black = color_make(0x100e09);
	obsidian = color_make(0x020403);
	black_grain = color_make(0x2c2c2a);
	black_magic = color_make(0x0b0510);
	iron_black = color_make(0x343432);
	rich_black_fogra29 = color_make(0x010b13);
	warm_black = color_make(0x004242);
	black_coral = color_make(0x54626f);
	black_shadows = color_make(0xbfafb2);
	black_raspberry = color_make(0x451425);
	kombu_green = color_make(0x354230);
	zinnwaldite_brown = color_make(0x2c1608);
	dark_slate_gray = color_make(0x2f4f4f);
	dark_charcoal = color_make(0x333333);
	russian_violet = color_make(0x32174d);
	dark_sienna = color_make(0x3c1414);
	alien_black = color_make(0x1a2228);
	black_chocolate = color_make(0x1b1811);
	blue_charcoal = color_make(0x262b2f);
	gothic_grape = color_make(0x120321);
	metropolis = color_make(0x1a1a1a);
	night_shadow = color_make(0x1c1c1c);
	off_black = color_make(0x595652);
	dark_raisin = color_make(0x1a0f0f);
	tea_bag = color_make(0x161311);
	electric_black = color_make(0x292929);
	tech_black = color_make(0x0d0e0e);
	dull_black = color_make(0x161616);
	dark_black = color_make(0x010203);
	natural_black = color_make(0x07000b);
	retro_black = color_make(0x1f201f);
	black_green_ral = color_make(0x303d3a);
	deep_black = color_make(0x050203);
	refresh_black = color_make(0x111212);
	rustic_black = color_make(0x1b1a16);
	rose_ebony = color_make(0x674846);
	liver = color_make(0x534b4f);
	purple_taupe = color_make(0x50404d);
	black_pearl = color_make(0x0e161a); 
	black_russian = color_make(0x24252b);
	aesthetic_black = color_make(0x1c1c1e);
	signal_black_ral = color_make(0x2b2b2c);
	cafe_noir = color_make(0x4b3621);
	luxury_black = color_make(0x060d0d);
	bright_black = color_make(0x222024);
	black_blue_ral = color_make(0x1a1e28);
	glossy_black = color_make(0x252324);
	ivory_black = color_make(0x231f20);
	pastel_black = color_make(0x1d1c1a);
	fashion_black = color_make(0x060403);
	graphite_black_ral = color_make(0x27292b);
	black_gray = color_make(0x303234);
	black_hole = color_make(0x060605);
	kokushoku = color_make(0x171412);
	kurotobi = color_make(0x351e1c);
	_void = color_make(0x010207);
	wet_suit = color_make(0x080706);
	yacht_club_black = color_make(0x222627);
	young_night = color_make(0x232323);
	blackstrap_molasses = color_make(0x2b2523);
	carbon_black = color_make(0x0c0a00);
	cynical_black = color_make(0x171717);
	black_plum = color_make(0x362b32);
	reversed_gray = color_make(0x080808);
	stout = color_make(0x0f0b0a);
	tornado_cloud = color_make(0x121213);
	walnut_hull = color_make(0x1b1813);
	tap_shoe = color_make(0x2a2b2d);
	woodsmoke = color_make(0x2b3230);
	black_red = color_make(0x3d2022);
	wind_cave = color_make(0x1f2024);
	heavy_gray = color_make(0x050505);
	arsenic = color_make(0x3b444b);
	ash_gray = color_make(0xb2beb5);
	battleship_gray = color_make(0x848482);
	black_coral = color_make(0x54626f);
	blue_gray = color_make(0x98afc7);
	cadet_gray = color_make(0x91a3b0);
	carbon_gray = color_make(0x625d5d);
	charcoal = color_make(0x36454f);
	cinereous = color_make(0x98817b);
	cool_gray = color_make(0x9090c0);
	dark_gray = color_make(0xa9a9a9);
	davys_gray = color_make(0x555555);
	deep_space_sparkle = color_make(0x4a646c);
	dim_gray = color_make(0x696969);
	gainsboro = color_make(0xdcdcdc);
	gray = color_make(0x808080);
	gray_cloud = color_make(0xb6b6b4);
	gray_dolphin = color_make(0x5c5858);
	gray_goose = color_make(0xd1d0ce);
	gray_green = color_make(0x5e716a);
	gray_wolf = color_make(0x504a4b);
	glaucous = color_make(0x6082b6);
	gunmetal = color_make(0x2a3439);
	jet = color_make(0x343434);
	jet_gray = color_make(0x616d7e);
	light_gray = color_make(0xd3d3d3);
	light_slate_gray = color_make(0x6d7b8d);
	marengo = color_make(0x4c5866);
	medium_gray = color_make(0xbebebe);
	nevada = color_make(0x666a6d);
	nickel = color_make(0x727472);
	old_silver = color_make(0x848482);
	outer_space = color_make(0x414a4c);
	rocket_metallic = color_make(0x8a7f8d);
	scorpion = color_make(0x5e5e5e);
	silver = color_make(0xc0c0c0);
	silver_chalice = color_make(0xacacac);
	slate_blue = color_make(0x737ca1);
	slate_gray = color_make(0x657383);
	smoke = color_make(0x738276);
	smokey_gray = color_make(0x726e6d);
	sonic_gray = color_make(0x757575);
	spanish_gray = color_make(0x989898);
	stone_gray = color_make(0x928e85);
	stormcloud = color_make(0x4f666a);
	taupe_gray = color_make(0x8b8589);
	timberwolf = color_make(0xdbd7d2);
	onyx = color_make(0x353839);
	paynes_gray = color_make(0x40404f);
	platinum = color_make(0xe5e4e2);
	pink_gray = color_make(0xe7dada);
	purple_gray = color_make(0xa7a6ba);
	rose_quartz = color_make(0xaa98a9);
	vampire_gray = color_make(0x565051);
	white_smoke = color_make(0xf5f5f5);
	xanadu = color_make(0x738678);
	bright_gray = color_make(0xe8e9eb);
	x11_gray = color_make(0xbbbcb6);
	dark_silver = color_make(0x746d69);
	pastel_gray = color_make(0xcccdc6);
	dusty_gray = color_make(0xb29ca2);
	misty_gray = color_make(0xbcc2c2);
	white_gray = color_make(0xf2f3f5);
	vintage_gray = color_make(0x989692);
	gentle_gray = color_make(0xdadada);
	zombie_gray = color_make(0x63645e);
	lavender_gray = color_make(0xc4c3d0);
	perfect_gray = color_make(0xa1a1a1);
	graphite_gray = color_make(0x4b4e53);
	rustic_gray = color_make(0xa6aba5);
	echo = color_make(0x898d86);
	window_gray = color_make(0x989ea1);
	silk_gray = color_make(0xb6b3a8);
	light_gunmetal = color_make(0x344148);
	silver_pink = color_make(0xc4aead);
	matte_silver = color_make(0xa5a5a8);
	rhythm = color_make(0x777696);
	pure_silver = color_make(0xc3c7c7);
	dark_charcoal = color_make(0x333333);
	best_gray = color_make(0x969892);
	agreeable_gray = color_make(0xd1cbc1);
	oxford_gray = color_make(0x8391a1);
	antique_pewter = color_make(0x808992);
	warm_gray = color_make(0x6e6259);
	sage_gray = color_make(0xb5bda5);
	dull_gray = color_make(0x8b837e);
	rich_gray = color_make(0x1f2022);
	ice_gray = color_make(0xbec3c6);
	gray_cmyk = color_make(0x939598);
	solid_gray = color_make(0x979797);
	electric_gray = color_make(0xa5adad);
	templeton_gray = color_make(0x788787);
	chrome = color_make(0xdbe2e9);
	sea_gray = color_make(0x9aa2a4);
	glossy_gray = color_make(0xafada9);
	anvil_gray = color_make(0x6b6b6b);
	chameleon_gray = color_make(0x686965);
	cement_gray = color_make(0x858a7e);
	steel_gray = color_make(0x888b8d);
	dorian_gray = color_make(0xaca79e);
	gun_smoke_gray = color_make(0x8a868e);
	camouflage_gray = color_make(0x545851);
	fashion_gray = color_make(0x8e8d8c);
	neutral_gray = color_make(0x898e8c);
	revere_pewter = color_make(0xccc7b9);
	olive_gray = color_make(0xa09f8d);
	metallic_gray = color_make(0xa8a9ad);
	french_gray = color_make(0xb4b19a);
	iron = color_make(0xa59c94);
	pale_smoke = color_make(0xcad4d1);
	bone = color_make(0xd7d2cb);
	heather = color_make(0x9aa297);
	true_silver = color_make(0x8a8d8f);
	power_gray = color_make(0x707272);
	storm_gray = color_make(0xb5bab6);
	ultimate_gray = color_make(0x939597);
	rhino = color_make(0xb9bbb6);
	harbor_gray = color_make(0xc7c6c1);
	seal = color_make(0x818380);
	anchor = color_make(0x3e424b);
	abalone = color_make(0xd6cfc7);
	fossil = color_make(0x787276);
	mink = color_make(0x888078);
	trout = color_make(0x979788);
	thunder = color_make(0xbdb7ab);
	shades_on = color_make(0x606060);
	lava = color_make(0x808588);
	stone_eagle = color_make(0xd8d9da);
	ice_cube = color_make(0xe3e4e0);
	porpoise = color_make(0x4d4d5c);
	flint = color_make(0x7e7d9c);
	dove = color_make(0x7c6e7f);
	gray_owl = color_make(0xd5d5cd);
	coin = color_make(0x9897a9);
	fog = color_make(0x655967);
	laid_back_gray = color_make(0xb4afa9);
	white = color_make(0xffffff);
	ghost_white = color_make(0xf8f8ff);
	white_smoke = color_make(0xf5f5f5);
	baby_powder = color_make(0xfefefa);
	snow = color_make(0xf5fefd);
	ivory = color_make(0xfffff0);
	floral_white = color_make(0xfffaf0);
	seashell = color_make(0xfff5ee);
	cornsilk = color_make(0xfff8dc);
	old_lace = color_make(0xfdf5e6);
	cream = color_make(0xfffdd0);
	beige = color_make(0xf5f5dc);
	parchment = color_make(0xf1e9d2);
	antique_white = color_make(0xfaebd7);
	champagne = color_make(0xf7e7ce);
	eggshell = color_make(0xf0ead6);
	dutch_white = color_make(0xefdfbb);
	bone = color_make(0xe3dac9);
	vanilla = color_make(0xf3e5ab);
	flax = color_make(0xeedc82);
	navajo_white = color_make(0xffdead);
	alabaster = color_make(0xedeae0);
	chiffon = color_make(0xfffacd);
	unresolved_problem = color_make(0xf3f2ed);
	old_wood = color_make(0xf0eee4);
	rose_white = color_make(0xfffafa);
	vista_white = color_make(0xfdfcfa);
	link_white = color_make(0xecf3f9);
	spring = color_make(0xf3f0e8);
	snow_drift = color_make(0xf8fbf8);
	peppermint = color_make(0xf1f9ec);
	merino = color_make(0xf2ebdd);
	half_and_half = color_make(0xffffe4);
	island_spice = color_make(0xfffcec);
	soft_peach = color_make(0xf6f1f4);
	harp = color_make(0xebf5f0);
	titan_white = color_make(0xeeeeff);
	audience_anger = color_make(0xeaf4fc);
	orange_white = color_make(0xf8f9f5);
	cough_mixture = color_make(0xf6f4f1);
	albescent_white = color_make(0xf3deca);
	coconut = color_make(0xfff1e6);
	pink_salt = color_make(0xf8eeec);
	frost = color_make(0xfcfbfc);
	linen = color_make(0xf3ead3);
	rice = color_make(0xfaf5ef);
	daisy = color_make(0xfafafa);
	powder = color_make(0xfbfcfa);
	pearl = color_make(0xfbfcf8);
	paris_white = color_make(0xc2d8d3);
	cup_cake = color_make(0xebf6f7);
	white_dove = color_make(0xf0efe7);
	white_whisper = color_make(0xeae8e1);
	lexicon = color_make(0xe7eaea);
	greek_villa = color_make(0xf0ebe3);
	white_diamond = color_make(0xe7e8e2);
	winter_white = color_make(0xdfdfd5);
	spatial_white = color_make(0xdedddb);
	hog_bristle_quarter = color_make(0xebe4d8);
	simply_white = color_make(0xefede3);
	oyster_white = color_make(0xe3dfd2);
	white_on_white = color_make(0xedefef);
	lexicon_quarter = color_make(0xf2f2f1);
	alice_blue = color_make(0xf0f8ff);
	honeydew = color_make(0xf0fff0);
	mint_cream = color_make(0xf5fffa);
	milk = color_make(0xfdfff5);
	pomelo_white = color_make(0xf9ffe3);
	anti_flash_white = color_make(0xf2f3f4);
	magnolia = color_make(0xf8f4ff);
	azure = color_make(0xf0ffff);
	huntington_white = color_make(0xf1f0e5);
	acadia_white = color_make(0xf4efe3);
	gainsboro = color_make(0xdcdcdc);
	mercury = color_make(0xe7e7e7);
	lavender_blush = color_make(0xfff0f5);
	isabelline = color_make(0xf4f0ec);
	bubbles = color_make(0xe7feff);
	glitter = color_make(0xe6e8fa);
	platinum = color_make(0xe5e4e2);
	cosmic_latte = color_make(0xfff8e7);
	blanched_almond = color_make(0xffebcd);
	light_yellow = color_make(0xffffe0);
	natural_white = color_make(0xeeece6);
	vivid_white = color_make(0xf8f8f4);
	white_wisp = color_make(0xe9e9e4);
	azureish_white = color_make(0xdbe9f4);
	timberwolf = color_make(0xdbd7d2);
	papaya_whip = color_make(0xffefd5);
	antique_white_usa = color_make(0xeeeae1);
	cola = color_make(0xf9edeb);
	atrium_white = color_make(0xf1eee4);
	cascading_white = color_make(0xf7f5f6);
	cotton_ball = color_make(0xf2f7fd);
	photon_white = color_make(0xf8f8e8);
	white_heat = color_make(0xfdf9ef);
	whitewash = color_make(0xfefffc);
	shadow_white = color_make(0xeef1ea);
	abbey_white = color_make(0xebe5d0);
	acoustic_white = color_make(0xefece1);
	aircraft_white = color_make(0xedf2f8);
	ceramic = color_make(0xfcfff9);
	coconut_butter = color_make(0xf2efe1);
	abstract_white = color_make(0xede9dd);
	bright_white = color_make(0xf4f5f0);
	broken_white = color_make(0xeeebe3);
	brilliant_white = color_make(0xedf1fe);
	commercial_white = color_make(0xedece6);
	feather_white = color_make(0xe7eae5);
	swan_white = color_make(0xfcfcfc);
	polar_bear = color_make(0xeae9e0);
	paper_white = color_make(0xf7fcfe);
	pacific_pearl = color_make(0xe8eae6);
	night_white = color_make(0xe1e1dd);
	delicate_white = color_make(0xf1f2ee);
	coconut_white = color_make(0xe9edf6);
	cake_batter = color_make(0xf0eddb);
	white_sand = color_make(0xece9e4);
	stone_white = color_make(0xfbf6f0);
	white_chocolate = color_make(0xede6d6);
	retro_white = color_make(0xedeae2);
}